### ISSUE TITLE
Add Loading Symbol to Pages

### ISSUE THREAD

**Issue by jnabity** [uno-isqa-8950/uno-cpi#1018]
When a user interacts with pages that include filters or processes that cause the page to take a long time to load, the screen should display a loading/spinning icon to indicate the application is processing.

**Comment by jnabity** [comment]
@jerrodanzalone @EdemD @Ruthie2018: I created this ticket for Sprint 5 as the development work associated to the research in #840. We will need a QA person assigned to this one @EdemD.

**Comment by EdemD** [comment]
@caadler as QA tester

**Comment by caadler** [comment]
@EdemD QA Passed:  
![image](https://user-images.githubusercontent.com/35402227/55677775-8ed19180-58b3-11e9-92c5-74aa89412791.png)

**Comment by EdemD** [comment]
Test document: https://drive.google.com/open?id=1HFIBGN7NLIHLy8hOB6tsYC8ztpaNeSgUeMob1xYKoVw
