### ISSUE TITLE
Fix Mobile Responsiveness of Navbar Throughout

### ISSUE THREAD

**Issue by jerrodanzalone** [uno-isqa-8950/uno-cpi#1021]
![image.png](https://images.zenhubusercontent.com/5c3a12df7e0c8903585df8a1/db839494-c68d-4e55-a72b-47ea648aa129)

Also, per the client: 
-"If I’m on charts on mobile, I cannot get back into any other analytics report/chart. That drop down doesn’t work."

**Comment by EdemD** [comment]
@shashankpatibandla as QA tester

**Comment by shashankpatibandla** [comment]
Login page
![image](https://user-images.githubusercontent.com/35643257/56587218-c411fb00-65a6-11e9-9b19-d6e4ba93c5be.png)
Audit Log
![image](https://user-images.githubusercontent.com/35643257/56587322-edcb2200-65a6-11e9-9095-3cc8234aec25.png)
Maps
![image](https://user-images.githubusercontent.com/35643257/56587432-223ede00-65a7-11e9-8849-a5cf02fc8c23.png)


This has been resolved. Tested on all the pages. Gave a couple of examples above.
