### ISSUE TITLE
Fix Header Color in Maps

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1022]
Update the header bar color in Community Partner Map, Legislative District Map, and Project Map.  The color should match the header in Community Partner Type map.

**Comment by EdemD** [comment]
@Ruthie2018 as QA tester

**Comment by Ruthie2018** [comment]
QA passed.

https://docs.google.com/spreadsheets/d/1INwFZmhWnjrczbjh5YutTLmYp2YBk-m2HddFLZKvshE/edit#gid=547627265
