### ISSUE TITLE
Data Points in Charts Missing

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1023]
I cannot replicate this, but Keristiena provided a screenshot below.  I think this is based on screen settings.
![image](https://user-images.githubusercontent.com/35402227/55350064-ce961480-5480-11e9-878d-d3e7ada90524.png)
![image](https://user-images.githubusercontent.com/35402227/55350074-d655b900-5480-11e9-8f85-b8eb33b33bd9.png)

**Comment by jerrodanzalone** [comment]
We will look at today during review - if we can't replicate move to closed.

**Comment by vbhat0891** [comment]
@vineethreddyramasa This is done right?

**Comment by jerrodanzalone** [comment]
Cannot replicate. Moving to closed.
