### ISSUE TITLE
Community Partner user error 

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#1036]
throws an error when trying to update community partner user![Screen Shot 2019-04-03 at 7.33.38 PM.png](https://images.zenhubusercontent.com/5c37dce5b7d8a251f243ca03/f29b5d28-fd90-48b4-9caf-01dc0ca6955e)

**Comment by jerrodanzalone** [comment]
@shashankpatibandla Please test this. I believe it is fixed based on last night's discussion.

**Comment by shashankpatibandla** [comment]
@jerrodanzalone I can replicate the same error in sta. Is this not pushed yet to sta and can I check with whoever fixed this?

**Comment by jerrodanzalone** [comment]
@EdemD Same note as 1037 :)

**Comment by EdemD** [comment]
Roger

**Comment by shashankpatibandla** [comment]
@EdemD Please test the profile picture as well. It should give a error when the picture is above 600*600 pixel or more than 10mb in size. The same with 1037. Thanks

**Comment by EdemD** [comment]
![image](https://user-images.githubusercontent.com/19415394/56541545-a9ea0580-6531-11e9-873e-45bfa1d73ba2.png)

![image](https://user-images.githubusercontent.com/19415394/56541783-490efd00-6532-11e9-8497-bf0552072496.png)

![image](https://user-images.githubusercontent.com/19415394/56541824-6643cb80-6532-11e9-9bfa-34e3532551d3.png)
