### ISSUE TITLE
Campus Partner user error

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#1037]
there is an error when trying to update campus partner user

**Comment by jerrodanzalone** [comment]
@shashankpatibandla If this is like the other ticket related to the avatar issue, can you please test. I believe that has been resolved. Otherwise, please move back into backlog.

**Comment by shashankpatibandla** [comment]
@jerrodanzalone The same with this, I can replicate in sta. let me know if it is not pushed or ask someone who fixed this

**Comment by jerrodanzalone** [comment]
@EdemD Please assign a tester and please make sure the update fields are tested thoroughly. Thanks!

**Comment by EdemD** [comment]
![image](https://user-images.githubusercontent.com/19415394/56465166-03312800-63be-11e9-8285-1896dc7662f8.png)

![image](https://user-images.githubusercontent.com/19415394/56465175-2eb41280-63be-11e9-9f7b-060082668dab.png)

Using  non EDU email also through a more descriptive error now: 
![image](https://user-images.githubusercontent.com/19415394/56465188-76d33500-63be-11e9-8984-249a3b62cc62.png)

![image](https://user-images.githubusercontent.com/19415394/56465196-9ec29880-63be-11e9-9032-7e0348bb5ab5.png)

**Comment by EdemD** [comment]
@jerrodanzalone please take a look at screenshots above if that covers it. I believe this is what we are testing. Let me know if otherwise. Thanks
