### ISSUE TITLE
Add Description for Reports and Charts within CMS

### ISSUE THREAD

**Issue by jerrodanzalone** [uno-isqa-8950/uno-cpi#1042]
As an admin, I want to be able to add descriptions to all report and charts from within the CMS.

**Comment by EdemD** [comment]
@caadler as QA tester

**Comment by caadler** [comment]
@EdemD QA Passed:  
![image](https://user-images.githubusercontent.com/35402227/55677823-8c236c00-58b4-11e9-98c2-0f10f17fd8bc.png)

**Comment by EdemD** [comment]
Test document: https://drive.google.com/open?id=19FqRfZBm_53xzxURMK_C7GEm5tWZa_5JqbnuXXbF3MY
