### ISSUE TITLE
Mobile Responsiveness - Register Campus Partner User

### ISSUE THREAD

**Issue by jnabity** [uno-isqa-8950/uno-cpi#1050]
The registerCampusPartnerUser url needs to be updated for mobile responsiveness.

URL: http://uno-cpi-sta.herokuapp.com/registerCampusPartnerUser/
Issue: When this link is opened and rotated to a portrait view, the ‘Campus Partner’ box moves out of frame.

![IMG_0150](https://user-images.githubusercontent.com/29965889/55670457-1c789700-584a-11e9-87a7-99ea5fdda688.jpg)

**Comment by vbhat0891** [comment]
![image](https://user-images.githubusercontent.com/26983338/56459267-bcf4ae00-6356-11e9-9497-0a486128f4b1.png)

**Comment by kalpanajha** [comment]
https://docs.google.com/spreadsheets/d/1DKL7oyKx3C1TmBHICYxmVeOT3JpfutbeUYKKHrOaVXE/edit#gid=6383154
