### ISSUE TITLE
Mobile Responsiveness - Register Community Partner

### ISSUE THREAD

**Issue by jnabity** [uno-isqa-8950/uno-cpi#1051]
The registerCommunityPartnerUser/ url needs to be updated for mobile responsiveness.

URL: https://uno-cpi-sta.herokuapp.com/partners/registerCommunityPartner/
Issue: When this link is opened, the ‘Website’ box does not align with the other items on the screen. This might not be a responsive thing, but calling it out regardless. This happens in both a landscape and portrait view.
![IMG_0148](https://user-images.githubusercontent.com/29965889/55670497-b3ddea00-584a-11e9-8e14-f8fb290c4ddf.jpg)

**Comment by vbhat0891** [comment]
The screenshot is for Register a Community Partner - the title and the link is for Register a Community Partner User.

**Comment by EdemD** [comment]
@kalpanajha as QA tester

**Comment by kalpanajha** [comment]
url box is mobile responsive.

https://docs.google.com/spreadsheets/d/15lfi12aaZLY4EUT8eIBhLJaG-sSs3zQQZUBhqtUjFM4/edit#gid=1723236634
