### ISSUE TITLE
Mobile Responsiveness - Mission Area Chart

### ISSUE THREAD

**Issue by jnabity** [uno-isqa-8950/uno-cpi#1052]
The missionchart/ url needs to be updated for mobile responsiveness.

URL: https://uno-cpi-sta.herokuapp.com/missionchart/
Issue: When the Mission Areas Chart is opened in Landscape view, the filters have some formatting issues as far as alignment. These are not present in portrait view of this page.
![IMG_0146](https://user-images.githubusercontent.com/29965889/55670519-0919fb80-584b-11e9-9a4b-9d585492a31e.jpg)

**Comment by EdemD** [comment]
@kalpanajha as QA tester

**Comment by kalpanajha** [comment]
the missionchart/ url is mobile responsive 

https://docs.google.com/spreadsheets/d/19VBkzHyEvhr6lsqvo4QzABqjGn3d3VTTAA8PQz63MkA/edit#gid=2139129299
