### ISSUE TITLE
Mobile Responsiveness - Mission Areas Report

### ISSUE THREAD

**Issue by jnabity** [uno-isqa-8950/uno-cpi#1054]
URL: https://uno-cpi-sta.herokuapp.com/projectInfo/
Issue: The spacing between the filter options is not equal between the top row. In the bottom row, the “CEC Building Partner” filter is pushing text to a new line for the data definition icon.
![IMG_0159](https://user-images.githubusercontent.com/29965889/55670554-9b220400-584b-11e9-9920-c0644299a3e8.jpg)

Issue 2: When in a portrait view, the filters are not aligned with each other.
![IMG_B3A3EFAF478C-1](https://user-images.githubusercontent.com/29965889/55670575-d58ba100-584b-11e9-8f93-855da628a3d4.jpeg)

**Comment by kalpanajha** [comment]
updating mission area report for mobile responsiveness

https://docs.google.com/spreadsheets/d/1SjGNSwwsx1PQYcPLshprbAoWzwnb_BqrhtaTPIpoYRQ/edit#gid=211443649
