### ISSUE TITLE
Mobile Responsiveness - Engagement Types Report

### ISSUE THREAD

**Issue by jnabity** [uno-isqa-8950/uno-cpi#1056]
URL: https://uno-cpi-sta.herokuapp.com/engageType/
Issue: The “CEC Building Partner” filter is pushing the data definition icon to the next line moving it out of alignment. Additionally, the “Campus Partner” filter is pushing outside of the box.
![IMG_0144](https://user-images.githubusercontent.com/29965889/55670631-898d2c00-584c-11e9-86f6-b12477cfc053.jpg)

**Comment by EdemD** [comment]
@caadler as QA tester

**Comment by caadler** [comment]
QA testing passed.  Tested with all phone sizes and iPads in Google Developer tools.
![image](https://user-images.githubusercontent.com/35402227/56460593-98a2cc80-636a-11e9-9fcf-fb99a328a059.png)
