### ISSUE TITLE
Mobile Responsiveness - Engagement Types Chart

### ISSUE THREAD

**Issue by jnabity** [uno-isqa-8950/uno-cpi#1057]
URL: https://uno-cpi-sta.herokuapp.com/engagementtypechart2/
Issue 1:The top line of filters are not equally spaced when in landscape view. The “CEC Building Partners” filter is moving the data definition icon to a new line and moving it out of alignment with the second line of filters. The “Campus Partners” filter is pushing outside the box.
![IMG_D17F9077BEFD-1](https://user-images.githubusercontent.com/29965889/55670647-c8bb7d00-584c-11e9-9302-e52b3b004cf7.jpeg)

Issue 2: In a portrait view, the left column of filters is not in alignment.
![IMG_B88ED561CBDD-1](https://user-images.githubusercontent.com/29965889/55670649-cbb66d80-584c-11e9-9172-c7ab373d5e5b.jpeg)

**Comment by EdemD** [comment]
@kalpanajha as QA tester
