### ISSUE TITLE
Mobile Responsiveness - Unique Partner and Community Count Report

### ISSUE THREAD

**Issue by jnabity** [uno-isqa-8950/uno-cpi#1058]
URL:
Issue 1: I do not think we are using this URL anymore.
Issue 2: When loaded, the Campus Partner filter moves outside the filter box.
![IMG_A514582590C5-1](https://user-images.githubusercontent.com/29965889/55670688-34054f00-584d-11e9-890c-d6ed867265f3.jpeg)

Issue 3: When in a portrait view, the filters overlap each other.
![IMG_43BCC6F05677-1](https://user-images.githubusercontent.com/29965889/55670697-4089a780-584d-11e9-9722-ac78834e1b26.jpeg)

**Comment by jerrodanzalone** [comment]
I'll delete this report. It's not being used.

**Comment by EdemD** [comment]
@duwaezuoke as QA tester

**Comment by Ruthie2018** [comment]
closed. this page is not used anymore
