### ISSUE TITLE
Mobile Responsiveness - Project Map

### ISSUE THREAD

**Issue by jnabity** [uno-isqa-8950/uno-cpi#1059]
URL: https://uno-cpi-sta.herokuapp.com/projectMap
Issue: The header details are moving the data definitions icon onto a new line. Is it possible to move the number as well if we move to a second line so it is not floating out there alone?
![IMG_8D82127CAB49-1](https://user-images.githubusercontent.com/29965889/55670728-92cac880-584d-11e9-88fa-c92a510b9d10.jpeg)

**Comment by EdemD** [comment]
@duwaezuoke as QA tester

**Comment by duwaezuoke** [comment]
QA tested and confirmed done. Reference: https://drive.google.com/open?id=1kT1zko-XTpKydjDlHFKDHd12aUvjrMup
