### ISSUE TITLE
Mobile Responsiveness - Community Partners Map

### ISSUE THREAD

**Issue by jnabity** [uno-isqa-8950/uno-cpi#1060]
URL: https://uno-cpi-sta.herokuapp.com/communityPartner
Issue: When in portrait view, the data definition icon is moved to a second line of text by itself. Can we move the number as well if we need to push to a second line?
![IMG_A07D610D7BAC-1](https://user-images.githubusercontent.com/29965889/55670749-d1608300-584d-11e9-8972-4eb5232dac14.jpeg)

**Comment by EdemD** [comment]
@duwaezuoke as QA tester

**Comment by duwaezuoke** [comment]
QA tested but the drop down button needs to be spaced out 
![image](https://user-images.githubusercontent.com/31281458/56160047-c7e0c480-5f8b-11e9-969f-e63aa159be9b.png)

**Comment by vbhat0891** [comment]
@duwaezuoke Can you test this again and let me know if it works better. I have reduced the font size of the title for mobile displays.

**Comment by duwaezuoke** [comment]
QA tested and confirmed done-done. Reference: https://drive.google.com/open?id=1Y-shafMJZR8P0MIZyRhrcp5ylYKK8OyU-P-b2V-tQ5w
