### ISSUE TITLE
Mobile Responsiveness - Community Partner Type Map

### ISSUE THREAD

**Issue by jnabity** [uno-isqa-8950/uno-cpi#1061]
URL: https://uno-cpi-sta.herokuapp.com/communityPartnerType
Issue: When in portrait view, the data definition icon is moved to a second line by itself. Can we move the number with the icon if we need to move to a new line?
![IMG_8AA00A08C082-1](https://user-images.githubusercontent.com/29965889/55670769-0371e500-584e-11e9-8d18-694b63082b66.jpeg)

**Comment by EdemD** [comment]
@caadler as QA tester
