### ISSUE TITLE
Mobile Responsiveness - Definitions Page

### ISSUE THREAD

**Issue by jnabity** [uno-isqa-8950/uno-cpi#1062]
URL: https://uno-cpi-sta.herokuapp.com/definitions
Issue 1: Do we still plan to utilize this URL for the final deliverable?

Issue 2: This page does not appear to be formatted like the other pages on the application. If we keep it, would like to update formatting and rename to ‘Terminology’ instead of ‘Terminologies’.
![IMG_AEA5306EE8C3-1](https://user-images.githubusercontent.com/29965889/55670892-349ee500-584f-11e9-99dc-993efca1f6be.jpeg)

**Comment by jerrodanzalone** [comment]
@Jantz021991 Can we delete this page?

**Comment by Jantz021991** [comment]
@jerrodanzalone  I will delete this page. This was based on the initial thought of having Data definition page in one which was eventually changed to what it is now 📦

**Comment by EdemD** [comment]
@caadler as QA tester

**Comment by Ruthie2018** [comment]
this page has been deleted so no more work is needed on this ticket.
