### ISSUE TITLE
Mobile Responsiveness - Community Partner My Projects Page

### ISSUE THREAD

**Issue by jnabity** [uno-isqa-8950/uno-cpi#1063]
URL: uno-cpi-sta.herokuapp.com/communitypartnerproject
Issue: There is a lot of white space after the 'My Projects' title on this page when loaded on the iPad.![IMG_D3889A57BCBA-1.jpeg](https://images.zenhubusercontent.com/5c36a4c8fdd1bf63fa7e173c/d17d4e5e-1edd-46c4-8a0d-a225d58269be)
![IMG_793487514E6C-1.jpeg](https://images.zenhubusercontent.com/5c36a4c8fdd1bf63fa7e173c/f7d3e3d8-7304-4aa0-b06a-56ca3b3891ce)

**Comment by shashankpatibandla** [comment]
@jerrodanzalone @jnabity This I believe is because of the loading icon. The loading icon shows up in that white space. Please let me know if otherwise

**Comment by shashankpatibandla** [comment]
@jnabity it's not a loading issue. we fixed this issue. It was a misspelling in the code

**Comment by EdemD** [comment]
@jnabity as QA tester

**Comment by jnabity** [comment]
This passed testing in STA for both mobile and browser.
https://docs.google.com/spreadsheets/d/1D7HUvhW8-8Hf9qIqtv-yXWEDMXn5TEyTowSuhWwd_LE/edit#gid=227356338
