### ISSUE TITLE
Data definitions in reports

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#1066]

**Comment by EdemD** [comment]
@shashankpatibandla as QA tester

**Comment by Jantz021991** [comment]
Data Definitions added to all the Reports - Need to check all the data tables in reports

**Comment by shashankpatibandla** [comment]
Testing document - https://docs.google.com/spreadsheets/d/14cyYu2D9WxbU1bkYkM9FaBLHe1vCFbrbkXRf1_EaEsg/edit#gid=468478632
