### ISSUE TITLE
Alphabetize "Colleges and Main Units" and "Campus Partners" filters list

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#1068]

**Comment by EdemD** [comment]
@caadler and @Ruthie2018 is this for all filters lists?

**Comment by EdemD** [comment]
Test document: https://drive.google.com/open?id=1-RIzczHoLbFt7DcIy-kbFvv04Tfdvvb1QlomM4pBHmk
