### ISSUE TITLE
Alphabetize and allow for sorting of Campus Partner and Community Partners in Add Projects form

### ISSUE THREAD

**Issue by jerrodanzalone** [uno-isqa-8950/uno-cpi#1126]
![image](https://user-images.githubusercontent.com/41122083/55824072-bc435880-5ac8-11e9-83b3-873bb1c99e22.png)

The drop-down list needs to be alphabetized. And some way to sort or search through it by typing the start would be helpful.

**Comment by EdemD** [comment]
@jnabity as QA tester

**Comment by jnabity** [comment]
I opened up the Create Project Form and the Campus Partner and Community Partner drop downs are alphabetized.
Test Script: https://docs.google.com/spreadsheets/d/1Kkt42gqOo68EYPuuRbk7ew3OcqkSRa3USAa5leB4HOc/edit#gid=227356338
