### ISSUE TITLE
Update Project Save Format

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1167]
Right now, projects are being saved as "Project Name :2017-18" .  They should be saved as "Project Name: 2017-18"   

The colon should be next to the project name, then a space, then the AY.

**Comment by EdemD** [comment]
@Ruthie2018 as QA tester

**Comment by vbhat0891** [comment]
This is dependent on the data in the database. If the data can be updated to have space between the color and year, it will reflect in maps infowindow and reports as well.

**Comment by caadler** [comment]
@vbhat0891 This is an easy change in the view.  Once new projects are saved with the correct format, I can update the existing projects in the DB without too much problem.

**Comment by vbhat0891** [comment]
This is updated in views, any new project added will have space between the colon and the year and not between the project name and colon. @caadler will be updating this for the existing data in production.

**Comment by Ruthie2018** [comment]
@edem  QA passed.

https://docs.google.com/spreadsheets/d/1yMfMCBLV-_bv_UE6s5pRi-zL4xyIf-uoPPDRFyu1hso/edit#gid=547627265
