### ISSUE TITLE
Alpha-Sort all filter variables – including in Maps, Reports, Charts and Forms

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1169]

**Comment by EdemD** [comment]
@Ruthie2018 as QA tester

**Comment by Ruthie2018** [comment]
@EdemD QA passed. per Craig the smaller lists don't absolutely need to be filtered

https://docs.google.com/spreadsheets/d/19mWbF1x-u4ZSYCHuJT3EFo2skCqRHFJ259OJzavF3JQ/edit#gid=547627265
