### ISSUE TITLE
Updates to Invite Community Partner form

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1170]
Per Client Feedback:
Change drop-down title to “Invite a Community Partner User”

Change this text “Enter the details of the Community Partner user that needs invitation”. To:
“A community partner user is an individual associated with a community partner organization. Inviting a community partner user will allow the user access to log into the Community Partnership Initiative and view their data, including project-level information. Submitting this form will trigger the user to receive an activation email.”

@Jantz021991 I think this is finished and just needs validation.

**Comment by caadler** [comment]
Verbiage for the password set page:
Title:
Registration Successful

Content:
Dear [name],
You are now registered as a community partner user which will allow you to view project-level data about your community organization’s partnership with UNO. Please click on the button below to create a password.

Button:
Create Password

@Jantz021991 This is for you.

**Comment by Jantz021991** [comment]
Thank you @caadler

**Comment by EdemD** [comment]
![image](https://user-images.githubusercontent.com/19415394/56460677-27641900-636c-11e9-9c3a-2e7af28776a6.png)
