### ISSUE TITLE
Updates to Community Partner Duplication Management

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1171]
Per Client Feedback:
Say the keyword = “Eastern”  , if we click the  Next Button more than once, the list  is getting appended each time instead of refresh. 
Searching a community partner that is already existed, like “AARP” click next button. Now change the value to any name that is not in the community partners data. The search function is not working. 

Could we move this list towards the left. It looks like it is centered.
Could we add a table around the partners 
Don’t bold the community partners. 
Change the text to: The following organizations are already registered as UNO community partners. Please ensure that the community partner that you intent to register is not in this list. 

The community partner report link is not working (time out error).
Either way - remove the link and the language: if yes, the community partner already exists! Click on the button below to access it.  

Change the language to: If you do not find the community partner in the list, please register the community partner.

Could we change it - in the instance that the search is not providing a list to - 

This community organization is currently not listed as a UNO community partner in this database. Please click on ‘Register the Community Partner’ and proceed with the registration. 

Change the Register Community Partner button to ‘Register the Community Partner’

**Comment by EdemD** [comment]
@pallavi0902 as QA tester

**Comment by pallavi0902** [comment]
QA test passed for everything except "remove the link and adding the the language: if yes, the community partner already exists! Click on the button below to access it." because under discussion with clients.
https://drive.google.com/file/d/12VUS0dOIECwaFQ_WPxWVnkApg3PFqfIM/view?usp=sharing
