### ISSUE TITLE
Update URL Field in Community Partner Form

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1172]
Per Client feedback:
The register a new community partner form is not allowing me to proceed with the website i have entered: it’s asking for a URL. “Please enter URL”

**Comment by jerrodanzalone** [comment]
Either create logic to add http to user input if it's not provided or create an error message asking for URL with http.

**Comment by caadler** [comment]
Per feedback:
Take off URL requirement on Community Partner registration.  Field needs to stay on the form, just not required.  If user does not enter a website, http cannot be saved in DB.
