### ISSUE TITLE
Community Partner Confirmation Page

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1173]
Per Client feedback:

Remove shadows
Add a period “Your organization is successfully registered as a UNO community partner.

**Comment by Jantz021991** [comment]
@caadler  Implemented the changes for both Campus partner registration and Community Partner Registration

**Comment by Jantz021991** [comment]
@EdemD Please assign a QA for this

**Comment by EdemD** [comment]
@pallavi0902 as QA tester

**Comment by EdemD** [comment]
https://drive.google.com/open?id=1DeK18U2LsSjk3h2I4-T-yKtFsumvJdEg
