### ISSUE TITLE
Invalid Items on Community Partner Form

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1175]
Per Client Feedback:
The “Register: A New Community Partner “, accepted the entry with numeric values for “State” and “Country” with same Primary and secondary mission value. No runtime error happened. ( Test2)

**Comment by jerrodanzalone** [comment]
There are packages in Django for countries if we want a drop-down there. For state, it's good enough to validate the correct char set.

**Comment by shashankpatibandla** [comment]
looks like this is a duplicate of #1177 . @pallavi0902 @jerrodanzalone @caadler @Ruthie2018 please look into this.

**Comment by caadler** [comment]
This is a duplicate of #1174, except this also includes a check for primary mission.  

As a side-note, #1177 is a similar ticket but for Campus Partners.
