### ISSUE TITLE
Updates for Register Campus Partner form

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1177]
Per Client Feedback:
Remove Exclamation mark from pop-up message for duplicate partner.

Change email message to “Please use your campus email (.edu) for the registration of a campus partner.”

**Comment by pallavi0902** [comment]
QA Test Passed : https://drive.google.com/file/d/1Km6pVpP3ToHbgTyYdRTk_jZVHW_z-_ty/view?usp=sharing
