### ISSUE TITLE
Updates to Register Campus Partner User form

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1178]
Per client feedback:
Change password message (in-page instructions and error message) to:
Your password should have at least 8 characters, 1 digit and 1 special character. 

Change pre-existing user error message to: A user with this email address is already registered. Once logged in, the user can be associated to multiple campus partners through the Organization portal. 

@Jantz021991 Are you working on this?

**Comment by Jantz021991** [comment]
Made changes to the form and changed the validation message-

![image](https://user-images.githubusercontent.com/26983295/56088077-d1104b00-5e3e-11e9-93fa-19b38c802868.png)

Changed the password message -
![image](https://user-images.githubusercontent.com/26983295/56088080-ef764680-5e3e-11e9-8968-a10e6d3b5dee.png)

**Comment by Jantz021991** [comment]
@caadler Implemented this in Django form validation, will work on beautifying text

**Comment by EdemD** [comment]
@shashankpatibandla as QA tester

**Comment by shashankpatibandla** [comment]
The form validations worked for all the invalid information. It also worked well with the valid information.
Test Document - https://docs.google.com/spreadsheets/d/1k8R1PVpkpOAx9T1U8lFQh3fBP7Rv4yPykbWQFqwXlFU/edit#gid=989992825

**Comment by caadler** [comment]
@shashankpatibandla @Jantz021991  The instructions have been updated but the error message still needs to be updated:
![image](https://user-images.githubusercontent.com/35402227/56173900-59b0f780-5fb5-11e9-8a63-eba4ed874c5a.png)

**Comment by EdemD** [comment]
@shashankpatibandla and @Jantz021991 Just fyi. Thanks
![1178](https://user-images.githubusercontent.com/19415394/56230462-e43f3880-6041-11e9-9fd9-e2e80819344f.png)

**Comment by Jantz021991** [comment]
Made the changes for password comment-
![image](https://user-images.githubusercontent.com/26983295/56327551-6f065d00-6140-11e9-91ba-d0a015917b4d.png)

**Comment by shashankpatibandla** [comment]
Confirmed the same - 
![image](https://user-images.githubusercontent.com/35643257/56375768-05cc2b80-61cc-11e9-98c0-67902d1f2779.png)

and moving to done
