### ISSUE TITLE
Add "Outcomes" to Project List and My Projects

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1179]

**Comment by Jantz021991** [comment]
@caadler This is done for Campus Partner user logins

**Comment by Jantz021991** [comment]
@caadler  done for Community Partner Project list as well

**Comment by Jantz021991** [comment]
@EdemD - Please assign a QA for this

**Comment by EdemD** [comment]
@Ruthie2018 as QA tester

**Comment by EdemD** [comment]
Test document : https://docs.google.com/spreadsheets/d/189tPcfiEBHLlpyvh_-7Syr5jiiK4x69DxrQ1S4n7szY/edit#gid=547627265

**Comment by Ruthie2018** [comment]
@Edem QA passed. https://docs.google.com/spreadsheets/d/189tPcfiEBHLlpyvh_-7Syr5jiiK4x69DxrQ1S4n7szY/edit#gid=547627265
