### ISSUE TITLE
Campus Partner User Email Requirement

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1182]
The email logic on the campus partner form and campus partner user form will not accept a @mail.unomaha.edu address or @gmav.unomaha.edu.

**Comment by EdemD** [comment]
@Ruthie2018 as QA tester

**Comment by Ruthie2018** [comment]
@edem  QA passed.

https://docs.google.com/spreadsheets/d/18f4jpFRK_reWHjCeVHXXNc8Gw-tQD9fZ5-LjHA8Wao0/edit#gid=547627265
