### ISSUE TITLE
Add a comma thousand separator in the reports. 

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1198]

**Comment by jerrodanzalone** [comment]
@duwaezuoke is the Dev on this

**Comment by EdemD** [comment]
![image](https://user-images.githubusercontent.com/19415394/56460543-f71b7b00-6369-11e9-9ab6-26650275b545.png)
![image](https://user-images.githubusercontent.com/19415394/56460566-2336fc00-636a-11e9-99be-420e3b8d7e58.png)
![image](https://user-images.githubusercontent.com/19415394/56460574-4f527d00-636a-11e9-94de-c9899554ce04.png)
