### ISSUE TITLE
Update email address

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1200]
Per Keristiena: 
The original email address that was provided cannot be used.  Please update all instances of "communityengagement@unomaha.edu" to "partnerships@unomaha.edu" throughout the system.  This includes the Contact Us email in the footer.

A search on the code in Github shows 10 instances of the old email address.

@jerrodanzalone @Jantz021991 @shashankpatibandla I'm not sure who is working on this, but you both commented on Slack, so here is the ticket.

**Comment by EdemD** [comment]
Test document: https://drive.google.com/open?id=1x4K9Ypy8yUUUrfaND33c7GDDLobF8PlOrj1unzQmsIw
