### ISSUE TITLE
Make the Footer More Responsive

### ISSUE THREAD

**Issue by jerrodanzalone** [uno-isqa-8950/uno-cpi#1216]
Adding javascript to make the footer more responsive to sizing changes. Please test in multiple browsers and as many devices as possible. Only applied to the pages extending base_home.html (so not home_page.html and no maps).

**Comment by jerrodanzalone** [comment]
@Edem Please assign a tester

**Comment by vbhat0891** [comment]
Tested on Internet Explorer, Edge, Firefox and Chrome. Also tested on mobile, it is responsive. Apart from the fact that the footer shifts to the bottom after page load, the footer works well. After discussing this with the team and confirming that it is acceptable, I am moving this to done.
