### ISSUE TITLE
Alternate color of rows for Project suggestion in Project validation page

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#1223]
alternate row highlighting on community partner and project dropdown.

**Comment by jerrodanzalone** [comment]
![image](https://user-images.githubusercontent.com/41122083/56389146-68ceba00-61ee-11e9-88ff-eba3bfd25179.png)
This is actually for the project validation screen and community partner validation screen.

**Comment by EdemD** [comment]
Project:
![image](https://user-images.githubusercontent.com/19415394/56460796-26cc8200-636e-11e9-987d-2615295a385e.png)Community Partner:
![image](https://user-images.githubusercontent.com/19415394/56460814-63987900-636e-11e9-8b71-f3a1ea3909db.png)
