### ISSUE TITLE
Community Partner Search not working

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#1224]
Community Partner search retains original list if searching for something else.  Project form is working as expected

**Comment by vbhat0891** [comment]
@EdemD Please assign a QA for this.

**Comment by EdemD** [comment]
![image](https://user-images.githubusercontent.com/19415394/56460880-68116180-636f-11e9-99e6-f2ae1993702e.png)

Reduced further when adding additional words
![image](https://user-images.githubusercontent.com/19415394/56460894-8ecf9800-636f-11e9-9e08-d760e0a0e1b4.png)
