### ISSUE TITLE
Left-align all description text on reports

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#1225]

**Comment by Ruthie2018** [comment]
@EdemD We need a QA for this ticket please

**Comment by EdemD** [comment]
@pallavi0902 as QA tester. Thanks

**Comment by pallavi0902** [comment]
QA Test Passed: https://drive.google.com/file/d/185CxI0xjIgbpi7LdGQCiuehOpfdN5r23/view?usp=sharing
