### ISSUE TITLE
Highlight validation errors

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#1226]
make sure that validation error messages are red/highlighted throughout the application.

Need to QA all.

**Comment by Jantz021991** [comment]
@jnabity  I have added in text to highlight validation errors in red. Please look into this and see if I am missing out pages

**Comment by jnabity** [comment]
Testing completed.
Script link: https://docs.google.com/spreadsheets/d/1xnccTkIc0tI2IeqFUMbE36YbTSNNO_e3KpyTq1WDDPs/edit
