### ISSUE TITLE
Terms & Conditions

### ISSUE THREAD

**Issue by jerrodanzalone** [uno-isqa-8950/uno-cpi#1248]
Add Terms & Conditions checkmark and (future) link to the terms and conditions that apply when a registering a campus or community partner with the app. 

![image.png](https://images.zenhubusercontent.com/5c3a12df7e0c8903585df8a1/06c71aef-434e-4f49-893b-779b7eacab92)

**Comment by jerrodanzalone** [comment]
@EdemD Please assign a tester.

**Comment by EdemD** [comment]
Project: 
![image](https://user-images.githubusercontent.com/19415394/56461022-9ee87700-6371-11e9-8cff-bc8b9251ed3e.png)

Community Partner: 
![image](https://user-images.githubusercontent.com/19415394/56461032-cf301580-6371-11e9-954a-2566bfe54dd0.png)

Campus Partner: 
![image](https://user-images.githubusercontent.com/19415394/56461045-ec64e400-6371-11e9-93de-516e1195cd43.png)

Community Partner user: 


Campus Partner user: 
![image](https://user-images.githubusercontent.com/19415394/56461062-2df58f00-6372-11e9-9a30-da1cf3d430ea.png)
