### ISSUE TITLE
relabel CEC filter

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#1252]
CEC building partner needs to be relabed as CEC Community Building Partner

**Comment by Ruthie2018** [comment]
@edem this will be ready for QA once it's merged

**Comment by EdemD** [comment]
Test document: https://drive.google.com/open?id=1c84X4AzS9GplLM5qrpnyiyghHYbnLiCpZ7z3RvS_la4
