### ISSUE TITLE
Add CMS snippets to additional pages

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#1293]

**Comment by jerrodanzalone** [comment]
@pallavi0902 I am still playing with the html, but you can test for functionality.

**Comment by caadler** [comment]
@jerrodanzalone Keristiena is requesting 2 more snippits to the Register Community Partner and the Create Project page.

**Comment by pallavi0902** [comment]
QA Test Passed https://drive.google.com/drive/u/0/folders/1HphhQDVJeHHbNlNzu_A7_GC3DoOeeJUK
