### ISSUE TITLE
Community partner report update

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#1294]
change filter to community partner primary mission area.  If not possible, remove the filter, and add a column for the primary mission area

Needs to be updated on public and private community report

**Comment by vineethreddyramasa** [comment]
Went with adding the Field...Removed the mission filter

**Comment by EdemD** [comment]
![image](https://user-images.githubusercontent.com/19415394/56826434-dcda1500-6821-11e9-96a0-6f9d2ed9b0af.png)

![image](https://user-images.githubusercontent.com/19415394/56826474-f24f3f00-6821-11e9-96e0-6f87e4d22781.png)
