### ISSUE TITLE
Address should not be required on Edit Projects

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1317]

**Comment by shashankpatibandla** [comment]
@EdemD tester required on this

**Comment by EdemD** [comment]
@kalpanajha as QA tester

**Comment by EdemD** [comment]
@kalpanajha as QA tester. Thanks

**Comment by EdemD** [comment]
![image](https://user-images.githubusercontent.com/19415394/56868225-2ad35200-69b5-11e9-88d8-d721b07d90a0.png)
