### ISSUE TITLE
UI Updates on Project Form

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1322]
Update partner help line to:
If you cannot find your campus partners and/or community partners in the list, please register them before submitting a new project form.

Partner help line and links should not be italicized.

Remove "Line 1" from Adress label.

**Comment by shashankpatibandla** [comment]
@EdemD Tester required.

**Comment by EdemD** [comment]
![1322](https://user-images.githubusercontent.com/19415394/56845325-0f692980-6885-11e9-9be0-524d4421c7bf.png)

![image](https://user-images.githubusercontent.com/19415394/56845337-3f183180-6885-11e9-9f22-e0e99037ea6a.png)
