### ISSUE TITLE
Update Verbiage on Project Search

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1324]
Top:
The following projects closely match your search and already exist in the database. Please ensure that the project you are trying to enter is not listed before proceeding. 

Before All Projects button:
Click on ‘All Projects’ to access a list of all community engagement projects in the database.

Before Create Project button:
To proceed with the creation of a new project, click on the button below.

**Comment by EdemD** [comment]
Updated:
