### ISSUE TITLE
Community Partner Search Verbiage Fix

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1325]
Please add a period. 
![image](https://user-images.githubusercontent.com/35402227/56771944-e4e07900-677d-11e9-87e8-8669302dacfe.png)

**Comment by EdemD** [comment]
![image](https://user-images.githubusercontent.com/19415394/56819423-4f8dc500-680f-11e9-9304-2fe9f8b10c6f.png)
