### ISSUE TITLE
Fix Campus Partner User Creation Error Message

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1326]
Note: at least (typo). Also, special character (no caps needed).
![image](https://user-images.githubusercontent.com/35402227/56771985-16f1db00-677e-11e9-93da-9c6a096d4b28.png)

**Comment by EdemD** [comment]
![image](https://user-images.githubusercontent.com/19415394/56824404-0d1eb500-681c-11e9-9831-b0ad9272e1d1.png)

![1326_Before](https://user-images.githubusercontent.com/19415394/56824422-13ad2c80-681c-11e9-97d3-ff8c5c5ae575.PNG)

![1326_After](https://user-images.githubusercontent.com/19415394/56824446-21fb4880-681c-11e9-8a0b-f44a3ceccf61.PNG)
