### ISSUE TITLE
Invite Community Partner User Verbiage Update

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1327]
A user with this email address is already registered. Please log into the portal...
![image](https://user-images.githubusercontent.com/35402227/56772031-456fb600-677e-11e9-8338-86d753a52076.png)

**Comment by EdemD** [comment]
![image](https://user-images.githubusercontent.com/19415394/56845399-4429b080-6886-11e9-92ae-7e8c0e36bd88.png)
