### ISSUE TITLE
CSV Export in "All Projects" page shows weird characters

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1328]

**Comment by vbhat0891** [comment]
@caadler This is on the export of "All Projects"  table I suppose, all the reports exported look fine to me.

**Comment by EdemD** [comment]
Before: 
![image](https://user-images.githubusercontent.com/19415394/56824661-bc5b8c00-681c-11e9-8af9-2e6d33ba725f.png)

After: 
![image](https://user-images.githubusercontent.com/19415394/56824695-cf6e5c00-681c-11e9-8677-3eadd211189a.png)
