### ISSUE TITLE
Update Filter Order in Reports and Charts

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1329]
![image](https://user-images.githubusercontent.com/35402227/56772096-85369d80-677e-11e9-9d0e-f09066013851.png)

**Comment by EdemD** [comment]
![image](https://user-images.githubusercontent.com/19415394/56868092-83095480-69b3-11e9-960f-1b0ac2979c36.png)

![image](https://user-images.githubusercontent.com/19415394/56868100-9fa58c80-69b3-11e9-84e2-3a5dbab0ae50.png)

![image](https://user-images.githubusercontent.com/19415394/56868108-b9df6a80-69b3-11e9-903c-28949c484733.png)

![image](https://user-images.githubusercontent.com/19415394/56868114-d1b6ee80-69b3-11e9-8c55-6d79543f1e29.png)

![image](https://user-images.githubusercontent.com/19415394/56868126-f27f4400-69b3-11e9-9ef2-a2d75d0c3d4e.png)

![image](https://user-images.githubusercontent.com/19415394/56868136-0a56c800-69b4-11e9-84f4-6d08c6514bf9.png)
