### ISSUE TITLE
Update Verbiage on Project Search

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#1330]
Add a period at the end of this sentence.
![image](https://user-images.githubusercontent.com/35402227/56772183-ccbd2980-677e-11e9-8193-4cbd77ecd50c.png)

**Comment by vbhat0891** [comment]
@caadler She gave an updated content for the project validation which is #1324 . You can close this ticket or move it to done.

**Comment by caadler** [comment]
Per comment, closing this ticket.
