### ISSUE TITLE
Change Email ID to Email

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#1352]
![image.png](https://images.zenhubusercontent.com/5c37dce5b7d8a251f243ca03/045e6101-9e31-4760-8746-fe5b5cbc4715)

**Comment by EdemD** [comment]
![image](https://user-images.githubusercontent.com/19415394/56845218-4dfde480-6883-11e9-8122-109537b27f59.png)

![image](https://user-images.githubusercontent.com/19415394/56845227-a3d28c80-6883-11e9-9cf5-8c85b10e1af6.png)
