### ISSUE TITLE
Mission Area details update

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#1355]
![image.png](https://images.zenhubusercontent.com/5c37dce5b7d8a251f243ca03/3dd49e9c-dda6-407a-a110-098b5446a0c3)

snippet is worked in a separate ticket.

**Comment by shashankpatibandla** [comment]
The primary shows up first. 
![image](https://user-images.githubusercontent.com/35643257/56843894-d3c26580-686c-11e9-805a-2c6f77d4f7c8.png)

**Comment by EdemD** [comment]
@caadler as QA tester. @caadler just throws a screenshot in here. That should suffice unless you want to make a test document. Thanks
