### ISSUE TITLE
Making header with same text font. 

### ISSUE THREAD

**Issue by shashankpatibandla** [uno-isqa-8950/uno-cpi#1359]

**Comment by shashankpatibandla** [comment]
![image](https://user-images.githubusercontent.com/35643257/56843932-4b909000-686d-11e9-9048-5efdb19a7bb5.png)

**Comment by shashankpatibandla** [comment]
Removed the bolds for consistency. Testers, Please check for bold text across the organization and user pages. Maybe even the whole application
![image](https://user-images.githubusercontent.com/35643257/56843939-6a8f2200-686d-11e9-8d1b-5fc4a74f942b.png)

**Comment by EdemD** [comment]
@Ruthie2018 as QA tester

**Comment by EdemD** [comment]
Changed for both campus and community partners

![image](https://user-images.githubusercontent.com/19415394/56868163-4f7afa00-69b4-11e9-906b-e6df7f2e54f3.png)

![image](https://user-images.githubusercontent.com/19415394/56868175-75a09a00-69b4-11e9-94a8-2e783c1c7f29.png)
