### ISSUE TITLE
Remove the option for campus partner user to edit College name

### ISSUE THREAD

**Issue by shashankpatibandla** [uno-isqa-8950/uno-cpi#1360]
![image.png](https://images.zenhubusercontent.com/5c36ccb57727940fef836f14/ecd2859a-0113-408c-ab8d-e7950f9d7991)

**Comment by shashankpatibandla** [comment]
Removed the edit button for campus partner org profile. Now the user can't access the edit page. But didn't remove code. Advice needed for the same.
![image](https://user-images.githubusercontent.com/35643257/56843968-eab58780-686d-11e9-890e-d39b88114813.png)

**Comment by EdemD** [comment]
@duwaezuoke as QA tester

**Comment by EdemD** [comment]
Before: 
![image](https://user-images.githubusercontent.com/19415394/56868295-0deb4e80-69b6-11e9-9297-63feedd0f623.png)
After: 
![image](https://user-images.githubusercontent.com/19415394/56868296-16dc2000-69b6-11e9-8730-0f58bb4565fc.png)
