### ISSUE TITLE
As a partner, I want to see a report listing projects.

### ISSUE THREAD

**Issue by TarekRamesses** [uno-isqa-8950/uno-cpi#18]
Projects should have these fields: 
- project name
- mission area
- community partner(s)
- campus partner(s)
- engagement type
- academic year

Can filter by:
- academic year
- campus partner
- mission area
- legislative district
- household income
- CEC partner

There will be additional private (campus only) information.

Private fields: 
- number of UNO students
- number of hours
- economic impact (hours * wage)

**Comment by indraTeja** [comment]
For multiple projects with campus partner - report is filing. 
Fix:
Use filter method. not get method. Create a list and pass it to filter(project_id__in = project.id)

![image](https://user-images.githubusercontent.com/13390222/48380201-79599200-e69c-11e8-841d-68c5f4573b41.png)


![capture](https://user-images.githubusercontent.com/13390222/48380028-def94e80-e69b-11e8-9fb9-7f708f48a589.PNG)

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49332142-28d3a700-f56d-11e8-9738-daaa02201f76.png)

Academic Year, CEC Partner, and Community type filter don't work. The page reloads but the data does not change.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49555900-3d92a080-f8c7-11e8-858f-2fa0adaf53a5.png)

I'm getting this error.

**Comment by TarekRamesses** [comment]
Still no all option for community type and cec partner filters.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49561016-9c154a00-f8da-11e8-8aa4-7f023c73d9ee.png)

The report just hides the community partner if they are filtered out. Instead, the entire project row should disappear.
