### ISSUE TITLE
Campus Partner Organization Profile

### ISSUE THREAD

**Issue by TarekRamesses** [uno-isqa-8950/uno-cpi#181]
A campus partner user should be able to view and edit their organization's profile.

**Comment by indraTeja** [comment]
**User is registred as SLA campus unit.**
<img width="960" alt="capture" src="https://user-images.githubusercontent.com/13390222/49182478-5e3b8300-f328-11e8-9928-3b814ec4d8cc.PNG">

**In his organization profile, its showing different cmapus unit.** 
<img width="960" alt="capture" src="https://user-images.githubusercontent.com/13390222/49182527-85925000-f328-11e8-8bd7-a4ec5dac2594.PNG">
