### ISSUE TITLE
Mission area report UI

### ISSUE THREAD

**Issue by TarekRamesses** [uno-isqa-8950/uno-cpi#190]

**Comment by indraTeja** [comment]
![capture](https://user-images.githubusercontent.com/13390222/46909709-86982b00-cefc-11e8-80bb-3ecda3e46dae.PNG)

**Comment by indraTeja** [comment]
![image](https://user-images.githubusercontent.com/13390222/47467614-ed4efb80-d7bc-11e8-887f-bb0fe6b353c2.png)
Completed. 
Moved to review/QA

**Comment by indraTeja** [comment]
![capture](https://user-images.githubusercontent.com/13390222/47622285-745be680-dad1-11e8-8ce5-c6920965fc00.PNG)

**Comment by indraTeja** [comment]
Changes made according to the sprint3 feedback
