### ISSUE TITLE
Application error/timeout when all academic years selected  

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2230]
-     From Projects Dropdown “All Projects” 
-     Card View  (Seems to be working okay on the table view side just slow) 
-     Filters selected (All academic years) 

![Application error or timeout 1](https://user-images.githubusercontent.com/44984230/216434099-fd20eb94-7baa-43b6-beb2-ab63318133a6.png)

**Comment by anguyen63** [comment]
Projects --> All Projects
Select All for the Academic Years drop down box --> Click Apply Filters.


![image](https://user-images.githubusercontent.com/117041118/235559513-5896a809-7a89-4cf5-acdb-deb0a264be09.png)
