### ISSUE TITLE
Project name not showing as entered

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2233]
6.	For example, the project named “Durango Days (Fall 2022): 2022-23 (2732)” doesn’t show the (Fall 2022) when it should. 
o	My understanding that everything but the unique id should show and that the capstone students in the most recent semester made updates to allow these symbols in the titles of projects and other areas of the tool like community partners.

**Comment by robynlloos** [comment]
![no parenthesis in project name showing 1](https://user-images.githubusercontent.com/44984230/216658656-fbcf6254-7b72-4e68-9455-094d46ce933f.JPG)
![no parenthesis in project name showing 2](https://user-images.githubusercontent.com/44984230/216658661-51a78f86-6b68-4726-beb3-c6b807641c4a.JPG)

**Comment by robynlloos** [comment]
Since the most recent capstone the "(Fall 2022)" details I added to each project name have all disappeared. We went in and made a substantial amount of edits to project names because of the duplicate titles for the UNO Service Learning Academy - this was our simple solution. Following the deployment of the previous capstone these no longer show.

**Comment by simranmakandar98** [comment]
This has been fixed on DEV and CAT, we will be promoting this to PROD soon

![image](https://user-images.githubusercontent.com/30575448/235558008-0c5fe85c-9971-4339-b894-3e693900d406.png)
