### ISSUE TITLE
Programming Error at /projectspublicreport/

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2235]
![Application error or timeout 1](https://user-images.githubusercontent.com/44984230/218215588-5eeeefbf-12ac-4fb2-b3e8-ccda5397a0d5.png)
[Uploading ProgrammingError at _projectspublicreport_.pdf…]()

**Comment by simranmakandar98** [comment]
Fixed on dev which will be promoted to CAT and PROD 

URL: https://uno-cpi-dev.herokuapp.com/projectspublicreport/

![image](https://user-images.githubusercontent.com/30575448/235557729-b20458c4-4ce6-4d21-8dfb-796e8bbaed0c.png)
