### ISSUE TITLE
Unable to delete log entry for user - which doesn't allow me to delete users no longer needed (who have access) 

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2277]
1. Went into log entries
2. looked up user
3. then clicked on log entry
4. no option to delete log entry

Thus unable to delete CEPI users who should no longer have access. 

![user-log-entry-unable to delete](https://user-images.githubusercontent.com/44984230/217879418-aab5e732-ce5b-4971-b273-ca34a0e656ce.JPG)
![user-log-entry](https://user-images.githubusercontent.com/44984230/217879410-45b4c1af-22aa-40df-b3ef-fafcea8cb248.JPG)

**Comment by anguyen63** [comment]
Log entry only records the newly created/deleted activities in the application. There shouldn't be any options to delete users. Admin users can delete users in the users table itself.
