### ISSUE TITLE
Create project search function not working

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2279]
When you search for a project in the search process when creating a new project - the search doesn't pull the projects even if there is one with the same name in the system. 

![create project search not working 1](https://user-images.githubusercontent.com/44984230/217962801-8972e435-3926-4f90-b6e2-b71608fb6521.JPG)
![create project search not working 2](https://user-images.githubusercontent.com/44984230/217962803-8422909d-b1f2-4391-aa8b-a5d126195c88.JPG)
system. Event with all academic years selected.

**Comment by anguyen63** [comment]
Refer to this https://github.com/uno-isqa-8950/uno-cpi/issues/2510
Search function didn't take into consideration the parentheses within the project name.
