### ISSUE TITLE
- [ ] Campus partner registration form should have unomaha.edu required email

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2280]
- [ ] Campus partner registration form should have unomaha.edu required email
![unomaha email for campus partner registration](https://user-images.githubusercontent.com/44984230/218219021-65ab1ace-9786-4e2d-a36b-6e27821dbfa1.JPG)

**Comment by anguyen63** [comment]
![image](https://user-images.githubusercontent.com/117041118/235564851-cbef0212-6fa1-4d9d-9f70-6e425588fbd6.png)
![image](https://user-images.githubusercontent.com/117041118/235564871-184e0dfa-b7dd-4eb5-a9b3-598de099e1b6.png)
When registering as a campus partner, the users must register with a @unomaha.edu account. Gmail account entered but it won't go through and the pop-up above will show.
