### ISSUE TITLE
Admin import function of project data

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2297]
We need a way to import long lists of projects that we know are not already within the system. For example, as we meet with faculty about their engaged work they report through alternative systems it is very time consuming to organize and enter 100's of projects at the end of every semester. 

The import function has been a part of the important needs since the beginning. Is this possible for the capstone or @MansiKamthan to assist with?

We would need to determine if excel would fit, formatting and order of columns.

**Comment by anguyen63** [comment]
The spreadsheet for bulk import is available. The file format is only importable in xls. 

https://unomail-my.sharepoint.com/:x:/r/personal/spawaskar_unomaha_edu/Documents/School/Teaching/Classrooms/23SP%20ISQA8950-002-MIS%20Capstone-CEPI/23SP-ISQA8950-002-Student%20Folder/Capstone%20Project%20Documentation/Sprint%20Deliverables/Sprint%202/Data%20Entry%20Import%20Sheet.xls?d=w83acdb6294b3425885b7fa378d5a91c8&csf=1&web=1&e=fpEpcR
