### ISSUE TITLE
DEV environment link in home page point to production site

### ISSUE THREAD

**Issue by kvelayutham1** [uno-isqa-8950/uno-cpi#2310]
[Defect - DEV environment links in home page points to production site.docx](https://github.com/uno-isqa-8950/uno-cpi/files/10810187/Defect.-.DEV.environment.links.in.home.page.points.to.production.site.docx)

https://uno-cpi-dev.herokuapp.com/

The links in home page for the below currently points to production site pages. It should point to pages in DEV environment. 

[REGISTER A NEW CAMPUS PARTNER](https://cepi.unomaha.edu/partners/register-Campus-Partner/)
[VIEW THE COMMUNITY PARTNER LEGISLATIVE MAP](https://cepi.unomaha.edu/legislative-District)
[VIEW PARTNER AND PROJECT ANALYTICS BY FOCUS AREA](https://cepi.unomaha.edu/projectInfo_public/)

**Comment by simranmakandar98** [comment]
@bkuduvar has fixed this issue via wagtail CMS
