### ISSUE TITLE
New User Error

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2311]
New user was added to the admin side of CEPI 
New user tried to log into the tool and this error was established after the duo authenti
[ValueError at_account.pdf](https://github.com/uno-isqa-8950/uno-cpi/files/10829043/ValueError.at_account.pdf)
cation process

@SachinPawaskarUNO @MansiKamthan

**Comment by robynlloos** [comment]
We deleted old wagtail users prior to this happening. Does wagtail users being deleted have implications on the users in the users area of CEPI admin?

**Comment by robynlloos** [comment]
After testing this with two people the following was determined:
1. When users are deleted from wagtail then they are deleted from the user panel of django
2. All users initially in the list of users that @MansiKamthan put together were deleted (we assumed no connection)
3. as a result then users were no longer able to access cepi as a campus user 
4. Tested this with two individuals 
5. also campus user box must be selected or the error attached here will happen

**Comment by simranmakandar98** [comment]
![image](https://github.com/uno-isqa-8950/uno-cpi/assets/30575448/37b00404-4b0d-45e9-b110-781ae0e937ad)

Solution: 
Ensure that "is active" and the appropriate check boxes are selected while creating the users. There will be a valueError when the right role is not selected.

This image shows an example for how campuspartneruser checkboxes must be selected.
