### ISSUE TITLE
Projects Report for Public User - Clicking Reset filter leads to login form

### ISSUE THREAD

**Issue by kvelayutham1** [uno-isqa-8950/uno-cpi#2333]
Projects Report for Public User - Clicking Reset filter leads to login form instead of resetting the filter options.

**Navigation:** Analytics -> Reports-> Projects
**Action:** Click Reset Filter
**Expected result** : It should refresh the filter options
**Actual result:** It goes to login form
It is the same in Dev and Production environment.

![Project_Defectpic1](https://user-images.githubusercontent.com/89324394/222237458-575a43ec-4177-4258-b941-fda2283f3df2.jpg)
![Project_Defectpic2](https://user-images.githubusercontent.com/89324394/222237464-898e34d1-89ae-4351-abf4-dc2d508e9043.jpg)

**Comment by kvelayutham1** [comment]
Completed retest and it is working fine now. related test scripts marked complete. 
[2333 Retest.docx](https://github.com/uno-isqa-8950/uno-cpi/files/11007415/2333.Retest.docx)

**Comment by kvelayutham1** [comment]
Re-opening the defect as the reset filter button redirects to public view of the report even it they are logged in as administrator and campus partner

[Reopen defect 2333.docx](https://github.com/uno-isqa-8950/uno-cpi/files/11206968/Reopen.defect.2333.docx)

**Comment by anguyen63** [comment]
Retest the defect. 
Analytics --> Reports --> Projects
Select All under Academic Years --> Apply Filters
Click Reset Filters.

![image](https://user-images.githubusercontent.com/117041118/235560668-e308dcde-c711-4c3f-8b5a-4ad25ae05d9a.png)
