### ISSUE TITLE
Mission area (Focus Area), Community partner, Campus partner not showing up for new projects created

### ISSUE THREAD

**Issue by kvelayutham1** [uno-isqa-8950/uno-cpi#2368]
Create Project – Issues list:

When a Campus partner user create a project using Create project Menu, the below details are not saved and thus the project is not visible in the respective reports – Community partner, Focus Area etc.
Mission area (Focus Area)
Community partner
Campus partner
Even in Admin panel, these data are not captured.
This bug is captured in 
[Create Project_Issues list.docx](https://github.com/uno-isqa-8950/uno-cpi/files/10945930/Create.Project_Issues.list.docx)

1.	DEV env, logged in as Campus user and Admin user.
2.	Local - Sprint 2 branch, logged in as Campus user and Admin user.
3.	Local – Master – logged in as campus user and Admin user. 
 
Screenshots attached.

**Comment by sakthipriya-07** [comment]
fix: added code to change the view restriction based on project status ("Drafts") in projects/views.py
Another Issue :Draft project displaying under My projects and My Drafts.
fix: Excluded the draft projects in My projects view. (projects/views.py)

Issue will be closed after review with Karpagam.

**Comment by kvelayutham1** [comment]
Create project and Draft project is able to save Focus area, community partner and Campus partner and show the same in reports. However, Edit draft/ Edit Project works fine for all fields except for Focus area, Campus partner, community partner and Topics. Tracked as part of defect #2395. Closing this defect. 
[2368 Defect retest.docx](https://github.com/uno-isqa-8950/uno-cpi/files/11007402/2368.Defect.retest.docx)
