### ISSUE TITLE
Duplicate contact information are added to same campus partner while registering it(part-1).

### ISSUE THREAD

**Issue by bkuduvar** [uno-isqa-8950/uno-cpi#2369]
Duplicate contact information are added to same campus partner while registering it.
1.	Dev env, logged in as campus partner and admin user.
2.	Master, logged in as campus partner and admin user.
[Duplicatecontactinformaationadded.docx](https://github.com/uno-isqa-8950/uno-cpi/files/10945976/Duplicatecontactinformaationadded.docx)

**Comment by simranmakandar98** [comment]
Completed: added unique_together for class Contacts in home\models.py
In progress: checking how to use contactdataarray[] to check for duplicates on form.
