### ISSUE TITLE
Respective focus area image is not displaying in the projects report.

### ISSUE THREAD

**Issue by bkuduvar** [uno-isqa-8950/uno-cpi#2370]
Respective focus area image is not displaying in the projects report.
1.	Dev, as public user.
2.	Local, master, as public user
3.	Prod, as public user.
[Focusareaimagesnotdisplaying.docx](https://github.com/uno-isqa-8950/uno-cpi/files/10946878/Focusareaimagesnotdisplaying.docx)

**Comment by Kowshik55** [comment]
Dev Anaylsis:

The image is from s3 bucket which is rendering from projects_public_view.html file(projects app)

**Comment by simranmakandar98** [comment]
**Cause:**
"Mission Image url" for each focus area is hardcoded in admin panel with object url from AWS S3.
**To inspect, go to:** Admin -> Home -> Mission areas

Currently in dev the S3 bucket name as seen in config vars is different from the hardcoded object url in mission image url field on admin.

**To fix:**
Update bucket names in object url on admin after checking that the folder structure is maintained correctly with objects present within it.
