### ISSUE TITLE
Existing 0 before data entry on Total UNO students and UNO student hours

### ISSUE THREAD

**Issue by anguyen2396** [uno-isqa-8950/uno-cpi#2371]
- dev, as campus partner
- local, as campus partner
[Total UNO students and UNO student hours.docx](https://github.com/uno-isqa-8950/uno-cpi/files/10947236/Total.UNO.students.and.UNO.student.hours.docx)

**Comment by simranmakandar98** [comment]
fix: removed default 0 from total_uno_students and total_uno_hours in projects\models.py

Issue will be closed after review with Anh.

**Comment by simranmakandar98** [comment]
default = 0 was removed from models which caused issue in form items.

**The fix:**
replaced with blank = True
