### ISSUE TITLE
Submit button to complete the project registration after editing draft project is saving the project as draft project. 

### ISSUE THREAD

**Issue by shireenbaboon** [uno-isqa-8950/uno-cpi#2396]
Submit button is not saving the project as new project instead project status is retained as draft. Screenshots explaining the scenario can be found in the following document.

[submitbutton.docx](https://github.com/uno-isqa-8950/uno-cpi/files/11004469/submitbutton.docx)

**Comment by anguyen63** [comment]
Issues only happen on independent local machine.
