### ISSUE TITLE
Defect in Focus Area Report; Engagement Types report; and Community Partner Report with specific data

### ISSUE THREAD

**Issue by kvelayutham1** [uno-isqa-8950/uno-cpi#2399]
**Defect in Focus Area Report; Engagement Types report; and Community Partner Report:**
Defect in DEV environment: 
Step 1: Navigation
Analytics-> Reports-> Focus Area Report
or
[Defect - Defect in reports.docx](https://github.com/uno-isqa-8950/uno-cpi/files/11035744/Defect.-.Defect.in.reports.docx)

Analytics-> Reports-> Engagement Types report
or
Analytics-> Reports-> Community Partner Report

Step 2: Filter selection
 Select 2022-23 in Academic Area filter.

Error Details
The error occurs specifically when I select Academic Year as 2022-2023
This contains projects added new after recent code changes.

**Comment by anguyen63** [comment]
Analytics-> Reports-> Focus Area Report
Select 2022-2023 under the Academic Years drop down --> Click Apply Filters.

![image](https://user-images.githubusercontent.com/117041118/235560369-6f57ccb5-f5a5-4822-b829-6344e346e30c.png)
