### ISSUE TITLE
SAML Response Error while logging in using .edu account

### ISSUE THREAD

**Issue by kvelayutham1** [uno-isqa-8950/uno-cpi#2480]
While trying to login using a .edu account, the below error is 
“Error in SAML response, Please contact system administration.”

[SAML error.docx](https://github.com/uno-isqa-8950/uno-cpi/files/11130135/SAML.error.docx)

**Comment by simranmakandar98** [comment]
fixed issue with bumped down versions.

`python3-saml==1.14.0
xmlsec==1.3.13
isodate==0.6.1
six==1.11.0
lxml==4.6.5`

- tested newest package versions
- tested on heroku stack 22

Above package versions only work on heroku stack 20 as of April 2023
