### ISSUE TITLE
Project Name-Append

### ISSUE THREAD

**Issue by TarekRamesses** [uno-isqa-8950/uno-cpi#251]
Projects should follow this format: Project Name: Academic Year (Number)

The academic year has to be appended to the project name, and then a number has to be incremented for each partner with that name already in the database.

**Comment by indraTeja** [comment]
<img width="960" alt="capture" src="https://user-images.githubusercontent.com/13390222/49179744-f9c8f580-f320-11e8-869c-6a7f5b6a701c.PNG">

I know this is not the right ticket to log this error, but I dint find the ticket for add project so I'm logging here. 

**Project add shows two columns, with an input field and a drop-down for the project. As per my understanding, we should get rid of the drop-down project name.**

**Comment by indraTeja** [comment]
Project drop-down is confusing. Search projects should be Search All projects.
View projects and search projects are confusing. So, please rename View projects to "My Projects". View projects are specific to the user projects and Search projects will show all the projects in the systems. It is confusing. 

<img width="954" alt="capture" src="https://user-images.githubusercontent.com/13390222/49182664-e0c44280-f328-11e8-9cd0-24af6ac0d761.PNG">

**Comment by indraTeja** [comment]
[AddProjects.docx](https://github.com/uno-isqa-8950/uno-cpi/files/2626742/AddProjects.docx)

**Comment by indraTeja** [comment]
@Arti012 @TarekRamesses: Add project is completely failing and fields are confusing. Please assign somebody. It is not just front-end fixable.

**Comment by indraTeja** [comment]
@TarekRamesses @Arti012 @SravaniKV 

I'm able to add the project as any campus partner. There are some minor fixes that need to be done.

I added a project named 'IT Innovation'. Append name should have syntax as 
<project name><space><academic year><space><(><Auto increament e.g 1 or 001><)>

But, in the databse it is saved as (74) after the academic year. I know its not an high impact defect, but I assume client wants to have the sequence for unique projects and increment from 001. 
![capture](https://user-images.githubusercontent.com/13390222/49249955-3ceb9d00-f3e3-11e8-9e39-10c958ab7e25.PNG)

**Comment by indraTeja** [comment]
@TarekRamesses @Arti012 @SravaniKV 
When I selected the academic year 2017-18, I must be able to only input semesters in this tenure. Suppose, in the academic year 2017-18, we have Spring-2017, Summer-2017, Fall-2017 and so on. But if I input Fall-2015, It should not be inserted into the database and add project should fail and through me an error in front-end form. This is need validation in the front end. 

![capture](https://user-images.githubusercontent.com/13390222/49250252-fea2ad80-f3e3-11e8-9660-6495550b70cd.PNG)

**Comment by indraTeja** [comment]
Okay, another major defect. I added a project using the add project form and it is added successfully into DB. But, once I goto 'View Project' page, I see no projects. Please correct me if my understanding is wrong or I missed any linking the project to campus partner. I think if I just add project it should be shown under View projects page. 

![capture](https://user-images.githubusercontent.com/13390222/49250836-89d07300-f3e5-11e8-8fa1-52240685d28b.PNG)
