### ISSUE TITLE
Project in drafts editing is not saving all the information entered

### ISSUE THREAD

**Issue by Kowshik55** [uno-isqa-8950/uno-cpi#2511]
![image](https://user-images.githubusercontent.com/30575448/235552864-ffe9a4c6-7943-474b-8bdd-41e0af6e12f1.png)

on myDrafts/ :
All edits are saved while editing drafts except project focus area, community partner, and campus partner

**Comment by anguyen63** [comment]
[Issues #2511.docx](https://github.com/uno-isqa-8950/uno-cpi/files/11368790/Issues.2511.docx)
