### ISSUE TITLE
Manual Testing

### ISSUE THREAD

**Issue by TarekRamesses** [uno-isqa-8950/uno-cpi#254]
Test pages and make comments on zenhub issues.

**Comment by ajanet379** [comment]
Community Partners column not showing anything 

![image](https://user-images.githubusercontent.com/31288748/48384606-bcbdfb80-e6b0-11e8-90bf-4a2aba00b973.png)

**Comment by ajanet379** [comment]
When there are more than one campus partners, separate them with a comma

![image](https://user-images.githubusercontent.com/31288748/48384642-e70fb900-e6b0-11e8-9e7a-50728a35b8a4.png)

**Comment by ajanet379** [comment]
Capitalize Engagement Type

![image](https://user-images.githubusercontent.com/31288748/48384683-0dcdef80-e6b1-11e8-9a2f-1f28e81d3842.png)

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/48395827-12f56380-e6de-11e8-87a4-0562d025f7a5.png)
![image](https://user-images.githubusercontent.com/22284674/48395843-21dc1600-e6de-11e8-9899-e5ae6975d974.png)

These forms should be consistent. Community partner has too much white space between it and header. Campus partner form is too thin and should be as wide as community partner. Community partner header text should also be bolded, and changed to Register: Community Partner User

**Comment by ajanet379** [comment]
![image](https://user-images.githubusercontent.com/31288748/48456043-21e22180-e783-11e8-8da5-85fa31f76830.png)
 The list doesn't show household income when I click on add more files.

**Comment by ajanet379** [comment]
Masking on fields -- Contact --First name, last name, workphone, cellphone.
The current scenario takes multiple primary contacts..?/
Masking on Campus partner name. 
Should the domain for campus partner be only "unomaha.edu". Currently it takes any domain.
![image](https://user-images.githubusercontent.com/31288748/48456340-52768b00-e784-11e8-82af-b25046925f8e.png)
![image](https://user-images.githubusercontent.com/31288748/48456357-66ba8800-e784-11e8-838e-ce472573ea48.png)
![image](https://user-images.githubusercontent.com/31288748/48456442-c153e400-e784-11e8-965c-eb4422dd8eaf.png)

**Comment by ajanet379** [comment]
![image](https://user-images.githubusercontent.com/31288748/48456764-d5e4ac00-e785-11e8-88cd-7afe19277f84.png)

The same with community organization

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/48515753-35df5f00-e827-11e8-99e4-53fe8401c83e.png)

Alignment is bad. Title should be changed. Two search bars is confusing. Maybe the show entries should be removed.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/48515884-a1293100-e827-11e8-9cfe-a8589947b0c0.png)

Description should be optional.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/48516000-e5b4cc80-e827-11e8-854c-5374bc906508.png)

These fields don't allow you to input characters, except for "e". Seems strange.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/48516199-5eb42400-e828-11e8-9f2c-028e699b0ea7.png)

When you click save, it will sometimes just do nothing. If you put letters into the number fields, it will tell you to use a number, as it should, but when you fix that, the save button just doesn't work without telling you why.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/48516354-c79b9c00-e828-11e8-96b3-29dd0d9ce75d.png)

Reports link doesn't work. Campus partners should also be able to see maps/analytics, and registering campus/community partners.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/48516536-3c6ed600-e829-11e8-8144-b4ee38d95a99.png)

I get an error when attempting to input new contact information. When I click save, it deletes all inputted information and says "Please correct the error below."

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/48516931-68d72200-e82a-11e8-9b67-0648ef26f805.png)
![image](https://user-images.githubusercontent.com/22284674/48516955-7c828880-e82a-11e8-97c5-725b45158c01.png)

I selected German and ended up with a different campus partner when I viewed my organization details, after logging in.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/48517317-88227f00-e82b-11e8-94c5-395a23619d6c.png)

The above information was accepted and submitted. Campus partner shouldn't allow numbers. Neither should names. Email should be forced .edu. Phone numbers have asterisks like they're required, but they're not, and should be.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/48517437-eea79d00-e82b-11e8-9f95-1c19d704179d.png)

The error message should be: "Please enter a phone number." I guess somebody already entered a blank cell phone so it's a repeat.

![image](https://user-images.githubusercontent.com/22284674/48517508-21ea2c00-e82c-11e8-89a9-cee99d8ef3cc.png)
![image](https://user-images.githubusercontent.com/22284674/48517521-30384800-e82c-11e8-9358-ad20bca8224f.png)

The above information was accepted. Work phone should be mandatory. Phone numbers shouldn't allow characters. Address information should be mandatory. The asterisk next to website should be removed.

![image](https://user-images.githubusercontent.com/22284674/48517590-7097c600-e82c-11e8-847f-022487f69002.png)

Numbers for names also shouldn't be accepted.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/48522896-e9544d80-e83f-11e8-89ff-b16f0ddb482a.png)

Community partner users shouldn't be forced to use a .edu email address.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/48577216-3be34780-e8dc-11e8-8095-482d9b5e8fdc.png)
Campus partner filter isn't working correctly: community partner isn't updated. Only community partners that have worked with that campus partner on a project should be counted.

**Comment by TarekRamesses** [comment]
The service learning engagement type is not in the database.

**Comment by TarekRamesses** [comment]
Projects report link brings up an error. The mission area chart has no data-it's blank.

**Comment by ajanet379** [comment]
![image](https://user-images.githubusercontent.com/31288748/48591843-51239a80-e90b-11e8-9333-fb57caa8bdc4.png)

Fix this bootstrap tag

**Comment by ajanet379** [comment]
> ![image](https://user-images.githubusercontent.com/22284674/48522896-e9544d80-e83f-11e8-89ff-b16f0ddb482a.png)
> 
> Community partner users shouldn't be forced to use a .edu email address.

**FIXED**

**Comment by ajanet379** [comment]
![image](https://user-images.githubusercontent.com/31288748/48728921-fa181100-ebfb-11e8-9985-363f15942d87.png)
 Request successful seems to be inconsistent to other signup pages

**Comment by ajanet379** [comment]
![image](https://user-images.githubusercontent.com/31288748/48729067-4b280500-ebfc-11e8-9413-d4572a6548cc.png)
 Community Partners and Campus Partners showing twice

**Comment by ajanet379** [comment]
![image](https://user-images.githubusercontent.com/31288748/48729134-790d4980-ebfc-11e8-8f4d-82d3c99816db.png)

Organization Profile page not working

**Comment by ajanet379** [comment]
>           The service learning engagement type is not in the database.

FIXED
