### ISSUE TITLE
Check project name is a mandatory field while creating a project.

### ISSUE THREAD

**Issue by bkuduvar** [uno-isqa-8950/uno-cpi#2606]
Removing project name in project registration page and clicking on next should give the error message "Project Name Required". Instead it is giving the error message " A project with this name and year already exists".

Please refer the attached screenshot for detailed instructions to recreate the issue.
[checkProjectmandatory.docx](https://github.com/uno-isqa-8950/uno-cpi/files/11422008/checkProjectmandatory.docx)

**Comment by simranmakandar98** [comment]
out of scope for SP23 capstone batch due to time constraint 

still leaving the issue open for later fix
