### ISSUE TITLE
Add UNO student hours total to exported data (all)

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2624]
Add UNO student hours total to exported data (all)

When we can see the total number of students per project we should see the hours as well. Check project report for Other Activity Type: [],the symbol should be replaced by 'None'.

**Comment by MansiKamthan** [comment]
Included in pull request SU23 CEPI Issue list fix_2 #2644

**Comment by robynlloos** [comment]
Hi Mansi!

Will you be pushing these to cat or are they ready to test? Let me know which ones I should test and I will do those here tomorrow or next week.

Robyn Loos, MA
Special Projects Associate
Barbara Weitz Community Engagement Center (115)
Office of Engagement | engage.unomaha.edu<https://www.unomaha.edu/office-of-engagement/index.php>
University of Nebraska Omaha | unomaha.edu<https://www.unomaha.edu/office-of-engagement/index.php>

Apply for CEC Office Space!<https://www.unomaha.edu/community-engagement-center/news/comm-spaceapp-release.php>

402.554.2173
***@***.******@***.***>

[Media:UniversityCommunications:Graphic Design:Brand tools:Logos- UNO:Vector files:Lock-up:Lockup-color on white backgrnd.eps]

CEC Inquiries: cec.unomaha.edu/contact<https://www.unomaha.edu/community-engagement-center/about-the-weitz-cec/contact.php>
Office Engagement Inquiries: engage.unomaha.edu/contact<https://www.unomaha.edu/office-of-engagement/contact.php>

***@***.***

**Comment by MansiKamthan** [comment]
Hi Ms.Robyn,

The changes are with professor for review,once they are approved I will push it to CAT environment for your testing.It should be in CAT by early next week.

Regards
Mansi

On Aug 9, 2023, at 12:11 PM, robynlloos ***@***.***> wrote:

﻿
Non-NU Email
________________________________


Hi Mansi!

Will you be pushing these to cat or are they ready to test? Let me know which ones I should test and I will do those here tomorrow or next week.

Robyn Loos, MA
Special Projects Associate
Barbara Weitz Community Engagement Center (115)
Office of Engagement | engage.unomaha.edu<https://www.unomaha.edu/office-of-engagement/index.php>
University of Nebraska Omaha | unomaha.edu<https://www.unomaha.edu/office-of-engagement/index.php>

Apply for CEC Office Space!<https://www.unomaha.edu/community-engagement-center/news/comm-spaceapp-release.php>

402.554.2173
***@***.******@***.***>

[Media:UniversityCommunications:Graphic Design:Brand tools:Logos- UNO:Vector files:Lock-up:Lockup-color on white backgrnd.eps]

CEC Inquiries: cec.unomaha.edu/contact<https://www.unomaha.edu/community-engagement-center/about-the-weitz-cec/contact.php>
Office Engagement Inquiries: engage.unomaha.edu/contact<https://www.unomaha.edu/office-of-engagement/contact.php>

***@***.***

**Comment by MansiKamthan** [comment]
Deployed in production
