### ISSUE TITLE
Inconsistent project data between reports

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2626]
The project count is not consistent across the reports.

**Comment by robynlloos** [comment]
@MansiKamthan and I met recently and the logic seems to be different between everything related to this. We agreed that the logic needs to be consistent throughout the tool and she is working on updating that on the back end to reflect only the start date of projects - the end data was utilized in the logic in some areas. Since the end date is optional data we both agreed this didn't make sense.

**Comment by MansiKamthan** [comment]
In Progress

**Comment by MansiKamthan** [comment]
Deployed in production
