### ISSUE TITLE
Make table view default

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2627]
For all project report make table view as default and card view as go to option.The rationale is from public and campus user perspective the table view allows people to search and export the data that they need.The card view does not have the option to search or export.

The ideal scenario will be to to remove card view to avoid switching between views and have simple design for the page.

**Comment by MansiKamthan** [comment]
In Progress

**Comment by MansiKamthan** [comment]
Included in pull request SU23 CEPI Issue list fix_2 #2644

**Comment by MansiKamthan** [comment]
Deployed in production
