### ISSUE TITLE
Unpublish following reports/charts from the tool 

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2628]
**Unpublish the following reports and charts from the tool - DO NOT DELETE WHAT HAS BEEN DEVELOPED ON THE BACK END.** 

**_Maps:_**

- Projects map
- Community partner types map (this is a filter within the community partners map)

**_Analytics > Charts:_**

- Focus area analysis
- Project partner trends
- Network analysis
- Partnership intensity analysis

**Comment by MansiKamthan** [comment]
In progress.

**Comment by MansiKamthan** [comment]
Included in pull request SU23 CEPI Issue list fix_2 #2644

**Comment by MansiKamthan** [comment]
Deployed in production
