### ISSUE TITLE
Pull together All Projects and Projects Report Pages

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2630]
When referring to the public and logged-in view, we should have one page that serves as both the report page for all projects (public reports) and the all projects page under the projects drop-down (logged-in view).

These pages have the same data, excluding the titles and summaries. This will simplify things in the future and allow us to enhance this via a one-page location rather than two. The public view of this page should show all the data related to projects and allow users to export (with ALL project data included in the export).

**Comment by robynlloos** [comment]
Keeping the projects report page and removing the one under projects drop down (all projects).

**Comment by MansiKamthan** [comment]
Deployed in production
