### ISSUE TITLE
Data Not Populating to Tables - Community Partner Report

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2635]
Data not populating from projects into tables. Noticed this initially in the community partner report.

**Comment by MansiKamthan** [comment]
Deployed in Cat environment for testing

**Comment by robynlloos** [comment]
I believe I tested this and replied in email if you can go back and review? Maybe add in comments here...

**Comment by MansiKamthan** [comment]
Deployed in production
