### ISSUE TITLE
Change to Community Partner Doesn't Updated

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2640]
**cat testing on 2023-06-26**
FYI: All testing was done using the project “Robyn data table test 2023-06-26: 2016-17 (2985)”

While testing in CAT to ensure the UNO student and k-12 data worked, I found a new issue with the community partner. When I edited a project, changing the community partner associated with that project, the changes didn't publish throughout the tool. See screenshots for more detail/clarification. When going back into the edit project, the new community partner did show, but no matter how many times I edited it and saved the project (with the new name), it did not work. 

![2023-06-26 Test Project Community Partner Not Updating 3](https://github.com/uno-isqa-8950/uno-cpi/assets/44984230/102d2d33-e025-4074-a1f2-18f6d4cc7a44)
![2023-06-26 Test Project Community Partner Not Updating 2](https://github.com/uno-isqa-8950/uno-cpi/assets/44984230/301e8c6e-8696-4a81-8678-6b1737bb5397)
![2023-06-26 Test Project Community Partner Not Updating 1](https://github.com/uno-isqa-8950/uno-cpi/assets/44984230/5b29c375-e3c1-4c0a-83d6-9d417e6ebe39)
![2023-06-26 Test Project Community Partner Not Updating](https://github.com/uno-isqa-8950/uno-cpi/assets/44984230/c57c291c-db95-4802-91fb-23ba046139a2)

**Comment by MansiKamthan** [comment]
Deployed in production
