### ISSUE TITLE
Maps Search Not Working

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2641]
Search bar on the community partners map not working again. This keeps happening while I am meeting with a community partners (which makes the tool look bad). 

![image](https://github.com/uno-isqa-8950/uno-cpi/assets/44984230/031cf489-4139-4e30-8a6b-f55c852f20f1)

**Comment by robynlloos** [comment]
I didn't check all the other maps.

**Comment by MansiKamthan** [comment]
@robynlloos Can you please try typing all letters in small like 'nami' instead of CAPS. It works for me on all maps.
For CAPS part I will check the code why it doesn't show up.

**Comment by MansiKamthan** [comment]
I have fixed the order of the projects showing in right click of the project circle in my local. Will test it for projects and push it to cat for your testing.

**Comment by MansiKamthan** [comment]
Deployed in production
