### ISSUE TITLE
Unpublish / change card view default to table view

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2648]
Make table view the default and unpublish card view from tool. If it is easiest to just change the default view to table for now that works, but eventually we do not need it published (but don't want to delete the historical info or code for it).

**Comment by robynlloos** [comment]
@MansiKamthan @SachinPawaskarUNO

**Comment by MansiKamthan** [comment]
Included in pull request SU23 CEPI Issue list fix_2 #2644

**Comment by MansiKamthan** [comment]
Deployed in production
