### ISSUE TITLE
duplicate projects

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2650]
When using the tool i noticed that there are a bunch of duplicate entries showing up which makes me worry that that last push from the previous capstone or sometime between there resulted in duplicate project data. See exported data. 
[
![duplicate projects](https://github.com/uno-isqa-8950/uno-cpi/assets/44984230/432b38d7-3d83-4543-9f90-68da9a1a15cc)
[Uploading Community Engagement Partnership Initiative-Projects Report (8).csv…]()
](url)

**Comment by robynlloos** [comment]
@MansiKamthan @SachinPawaskarUNO

**Comment by MansiKamthan** [comment]
Deployed in production
