### ISSUE TITLE
Projects entered not showing focus areas or community partners in the all projects report

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#2651]
New campus user added and submitted project. Community partners, campus partner, and focus areas not showing in submitted project data in.
![MicrosoftTeams-image (3)](https://github.com/uno-isqa-8950/uno-cpi/assets/44984230/bf848368-c027-4ddf-b5a1-00900e20dc4e)
![MicrosoftTeams-image (1)](https://github.com/uno-isqa-8950/uno-cpi/assets/44984230/a9f17b2a-5f4a-4925-b1e7-fd83ba9f538d)

![MicrosoftTeams-image](https://github.com/uno-isqa-8950/uno-cpi/assets/44984230/c779ae70-d00e-4d1d-a78b-37411242a0e4)

**Comment by MansiKamthan** [comment]
Deployed in production
