### ISSUE TITLE
Adding Course Details to Project

### ISSUE THREAD

**Issue by TarekRamesses** [uno-isqa-8950/uno-cpi#276]
If a campus partner selects Service Learning as the engagement type of a project, then course details should appear so he can associate a course with the project. This is true both for add and update project.

**Comment by indraTeja** [comment]
move this to the product backlog or discard this ticket if projects don't need this course association.  We can discuss this in class, I don't see anywhere in project form we are inputting this field. @TarekRamesses @Arti012
