### ISSUE TITLE
Map UI

### ISSUE THREAD

**Issue by TarekRamesses** [uno-isqa-8950/uno-cpi#299]
Fixing alignment, implementing the slideable sidebar to all maps. Other UI fixes.

**Comment by indraTeja** [comment]
http://127.0.0.1:8000/, the homepage is taking a long time to load.

**Comment by indraTeja** [comment]
@Minhduong243 @MinhduongUNO @Arti012 @Goutham2591 
Homepage, Legislative district, Household income, Projects maps are loading very slow. Is there any way to make it quicker?

**Comment by indraTeja** [comment]
We don't want to wait so long in the demo to load the map. It takes me 2-5 min to load the map, we need to discuss this n get it fixed.
