### ISSUE TITLE
Make the website responsive to different browsers, browser sizing, mobile, tablet, etc.

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#321]
The application isn't working in Internet Explorer. Please test functionality in Firefox and Edge.

**Comment by robynlloos** [comment]
o	People should be able to view this tool within any device and when sizing down the browser with the tool automatically updating to fit that device
•	When doing this please reference the order of how UNO website pages display on different devices – for example when on a mobile device looking at an article the main information comes first and the sidebar information drops below.

**Comment by jerrodanzalone** [comment]
Make separate tickets for each page that requires an update. Only pages that are not behind a log-in screen.
