### ISSUE TITLE
Project Add/Edit/View/Search Updates

### ISSUE THREAD

**Issue by TarekRamesses** [uno-isqa-8950/uno-cpi#367]
Project add button isn't working. Forms should have consistent forms/columns.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49261462-f52b3c80-f407-11e8-9382-fb6e81e0e152.png)

Academic Year filter does nothing.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49261542-4b987b00-f408-11e8-83a8-e7e93b253553.png)

Going to the Project tab as a community partner causes this error.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49332526-1d37ae80-f574-11e8-9353-77f24a5285cd.png)

I can't type anything in zip except for numbers.....but I can also enter e for some reason.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49332803-63dbd780-f579-11e8-9c84-415772714d99.png)

These first two fields don't have the front-end validation. Can input es.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49332923-9be41a00-f57b-11e8-85b9-2b842c673bbb.png)

I get front-end error messages, but I can still submit.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49332933-c7ff9b00-f57b-11e8-96d3-110d77bfc8c3.png)

Mission area should be mandatory.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49332971-51af6880-f57c-11e8-951d-0879d395c49a.png)

Campus partner shows project name.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49332980-6b50b000-f57c-11e8-941c-bfbb5bed3ea7.png)

When I only select a campus partner and not a community partner, and enter data for campus partner volunteers and submit, it populates the campus partner volunteers value into the community partner volunteer field and says community partner is required.

**Comment by SravaniKV** [comment]
> ![image](https://user-images.githubusercontent.com/22284674/49332803-63dbd780-f579-11e8-9c84-415772714d99.png)
> 
> These first two fields don't have the front-end validation. Can input es.
Hi Tarek, The system or the validating is considering 'e' as numeric(like exponential) so it will allow 'e' always but no other alphabets

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49411732-a9420580-f72f-11e8-88c8-54b180d5522e.png)

This field is not editable in project edit for some reason.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49411868-21a8c680-f730-11e8-80a5-a76f32829ea7.png)

Error when trying to add myself to a project.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49412402-ed360a00-f731-11e8-9fa0-fea4f47e82f6.png)

Trying to update project throws this error.

**Comment by Arti012** [comment]
This had been fixed with the current code . Cross retest  and close .

**Comment by Arti012** [comment]
this has been fixed with the current code .Retest and close

**Comment by Arti012** [comment]
Fixed with current code .Retest and Close

**Comment by Arti012** [comment]
fixed with current code .Retest and close

**Comment by Arti012** [comment]
The update will work if u have all the integer values in the projects. So
when u add ...add all values hrs etc and u should be able to update.Just
now tried creating a project in Heroku and edited it.

**Comment by TarekRamesses** [comment]
There should be a field called Primary Mission Area and then the form should just have other mission areas. User should not select mission type. Currently, they can have an other mission area and no primary.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49480362-0c916d80-f7ec-11e8-8b2c-4d24b76c5f40.png)
![image](https://user-images.githubusercontent.com/22284674/49480375-1915c600-f7ec-11e8-954b-1bcada359057.png)
![image](https://user-images.githubusercontent.com/22284674/49480395-2632b500-f7ec-11e8-9585-0ec2f5a6c67a.png)
![image](https://user-images.githubusercontent.com/22284674/49480434-4c585500-f7ec-11e8-841e-3762bc919f79.png)
![image](https://user-images.githubusercontent.com/22284674/49480456-62661580-f7ec-11e8-8858-552caf9aa372.png)

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49480551-ba048100-f7ec-11e8-820c-7f68cc6eda4e.png)

Doesn't show second community partner or mission area.

**Comment by TarekRamesses** [comment]
When I select my campus partner originally and add the project, I am taken to my projects and it has not been added. I have to go find it in search projects and add myself.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49623426-4486e500-f993-11e8-9e3f-39c962a23f56.png)
![image](https://user-images.githubusercontent.com/22284674/49623434-4a7cc600-f993-11e8-9e75-713b416b5973.png)

Course details appear for wrong engagement type. It should be service learning instead of providing access.

**Comment by TarekRamesses** [comment]
Why can they enter uno student hours when adding a project when it just says none regardless. Remove the field. And although it is calculated by multiplying hours and volunteers, it only works when editing a project. When adding a project, even if I put values for UNO Student Hours, and campus partner volunteers and hours, it says None. And if we have this logic for hours, why don't we have it for students too? Those are added for each class or campus partner.
