### ISSUE TITLE
Front-end form validation

### ISSUE THREAD

**Issue by TarekRamesses** [uno-isqa-8950/uno-cpi#370]
Relevant error messages should show the user what they did wrong, and where.

**Comment by indraTeja** [comment]
Phone number should be 10 digit, it takes more than 10. Either change the model or handle it in front end form validation.

<img width="960" alt="capture" src="https://user-images.githubusercontent.com/13390222/49180360-698bb000-f322-11e8-9ec3-42aab39d1f22.PNG">
