### ISSUE TITLE
Manual Testing Sprint 6

### ISSUE THREAD

**Issue by TarekRamesses** [uno-isqa-8950/uno-cpi#371]

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49193523-f7789280-f344-11e8-98f0-30541e584a4e.png)

There's no way for a new campus or community partner to check to see if their organization already exists in the system. There should be a check if your organization is here dropdown.

**Comment by Arti012** [comment]
If the organization already exists the form wont allow them to submit
duplicate record..It prompts on submission " Community partner already
exists
"

**Comment by TarekRamesses** [comment]
I understand that, but that means any community partner beginning to use the system will try and create their organizational profile. That opens the door for a typo in the name to create duplicate records, and they have to enter the entire form just to know if their community/campus partner exists. Seems less than ideal.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49243231-6e0fa180-f3d2-11e8-941d-2ad4b904b70c.png)

Engagement Type report doesn't appear to be working.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49255637-37e21a00-f3f2-11e8-9d17-39cc47a26d5d.png)

Get this error when submitting a community partner. It also accepted the below input:

![image](https://user-images.githubusercontent.com/22284674/49255660-53e5bb80-f3f2-11e8-9ac5-dd9828604786.png)
![image](https://user-images.githubusercontent.com/22284674/49255679-5d6f2380-f3f2-11e8-9238-0ab6943bafb7.png)

So phone numbers aren't a full 10 digits, zip code has characters, and there was no mission area selected.

**Comment by IndraTeja** [comment]
We may not show upload in final demo.
