### ISSUE TITLE
Campus Partner Organization Registration

### ISSUE THREAD

**Issue by TarekRamesses** [uno-isqa-8950/uno-cpi#44]

**Comment by TarekRamesses** [comment]
Registration pages for community partner member, campus partner member. Also registration pages for new campus and community partners.

**Comment by indraTeja** [comment]
Cosmetic defects found such as field alignment and phone number field is accepting char. Please ref to document for details : https://docs.google.com/document/d/1irs5aqhFWWOxp_bg1lrUrVeFfLPqwzmToQRDO25K4j8/edit#
![capture](https://user-images.githubusercontent.com/13390222/46823854-e6ec6880-cd54-11e8-92ff-
53ba3ceec3a4.PNG)

**Comment by indraTeja** [comment]
Overall functionality is working as expected. Just UI needs improvement.
