### ISSUE TITLE
Reporting - data discrepancy - CEC Partner

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#453]
Reports data discrepancy

All is 50, Yes 2 and No 47. Numbers not adding up

![image](https://user-images.githubusercontent.com/44984207/50240696-07efbc00-038b-11e9-8028-3505019a64a2.png)

**Comment by EdemD** [comment]
https://docs.google.com/spreadsheets/d/1dZX7j9AOOGbuxg8K8K3bV347SpFlDMp6JGMM8y9nE_0/edit#gid=547627265
