### ISSUE TITLE
Campus Partner - University structure

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#454]
All reporting, including Maps, Reports, Charts - should accommodate the university structure. Each report/map/chart should include a filter for College/Main Unit and a cascading filter for Department/School/Unit

o	If a user selects Athletics, the second filter should only show units associated with Athletics. This way you can view the data based on the entire college (college selected) and all units selected, or based on a particular unit. 
o	The order of these colleges/departments should be alphabetical.

**Comment by Ruthie2018** [comment]
move college above campus partner and then cascade options by college selected
