### ISSUE TITLE
Filter Responsiveness 

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#455]
The data is not responsive to this filter: 
![image](https://user-images.githubusercontent.com/44984207/50788990-8e0f6c00-1280-11e9-8c95-b584c6d48f6f.png)

**Comment by Keristiena** [comment]
![image](https://user-images.githubusercontent.com/44984207/50789149-070ec380-1281-11e9-94b3-02ca2c54e6e2.png)

**Comment by Keristiena** [comment]
![image](https://user-images.githubusercontent.com/44984207/50789182-24439200-1281-11e9-9c96-04aa8a687480.png)

**Comment by jnabity** [comment]
Testing passed. Script below:
https://docs.google.com/spreadsheets/d/1UOlBf1sM23ke2B_h_6UamVE-6-eZBpscjFkBUbsRZ7o/edit#gid=227356338
