### ISSUE TITLE
Mission Area Report: remove search box

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#456]
There is no reason to keep the search box here: 
![image](https://user-images.githubusercontent.com/44984207/50789261-5ead2f00-1281-11e9-9d46-66b855380854.png)

**Comment by EdemD** [comment]
@pallavi0902 as QA tester

**Comment by EdemD** [comment]
https://drive.google.com/open?id=1a4EzM_jZkkE89KThFKWsVP6GA8XrVof0cFa4xtQKcAs
