### ISSUE TITLE
Report: Engagement Type

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#458]
Only a small part of the data shows up here; it seems to be filtered based on this type. 
![image](https://user-images.githubusercontent.com/44984207/50789431-dbd8a400-1281-11e9-970c-6019a7aef5cb.png)

**Comment by Ruthie2018** [comment]
https://docs.google.com/spreadsheets/d/1oe3yVl23jmWEJJEwMMEMZmFaOzE8IDZb40XwkmtF2Oc/edit#gid=547627265
