### ISSUE TITLE
Report: Engagement Type

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#459]
Add columns for number of **unique community partners** and if possible, number of unique campus partners.

**Comment by shashankpatibandla** [comment]
@jerrodanzalone & @EdemD . This ticket is merged with pull request #861

**Comment by EdemD** [comment]
Filtering is not working as intended

**Comment by EdemD** [comment]
Query tested
`-- ENGAGEMENT TYPE REPORT
select distinct e.name engagement_type
  ,count(distinct p.project_name) Projects
	,count(distinct pp.community_partner_id) CommPartners
	,count(distinct pp2.campus_partner_id) CampPartners
	,sum(p.total_uno_students) numberofunostudents
	,sum(p.total_uno_hours) unostudentshours
from projects_project p
  left join projects_engagementtype e on e.id = p.engagement_type_id
 	left join projects_projectcommunitypartner pp on p.id = pp.project_name_id
	left join projects_projectcampuspartner pp2 on p.id = pp2.project_name_id
-- where p.academic_year_id = 1
group by p.engagement_type_id, e.name
order by engagement_type;
`
