### ISSUE TITLE
Report: Community Partners - Data Discrepency

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#460]
The numbers in this report don't seem to be adding up - compare the following screenshots:

![image](https://user-images.githubusercontent.com/44984207/50790111-a0d77000-1283-11e9-89ae-98e91cb170b4.png)

![image](https://user-images.githubusercontent.com/44984207/50790116-a765e780-1283-11e9-9ef2-c906dccf1e66.png)

![image](https://user-images.githubusercontent.com/44984207/50790119-aa60d800-1283-11e9-99dd-7387b20d1186.png)

![image](https://user-images.githubusercontent.com/44984207/50790123-acc33200-1283-11e9-91a6-03b3d6ce48f3.png)

**Comment by caadler** [comment]
@EdemD  QA successfully tested both Public and private report.

**Comment by EdemD** [comment]
https://docs.google.com/spreadsheets/d/1nNtAaIzJT-1kUt7YJrOfPcUxFAu2ojQcYqN11wgq_Eo/edit#gid=547627265
