### ISSUE TITLE
Report: Community Partner - Filter Responsiveness

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#461]
The report does not react based on the Mission Area filter: 
![image](https://user-images.githubusercontent.com/44984207/50790302-370b9600-1284-11e9-9f8d-f4b17b1fdc67.png)

**Comment by caadler** [comment]
Possibly related to #455

**Comment by caadler** [comment]
@EdemD  QA tested successfully for both private report and public report
