### ISSUE TITLE
'All' Option in All Filters

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#462]
Whereas the default of each filter is 'All ...', once i have selected a different variable in a filter, i sometimes am unable to select the All. See the following example:
![image](https://user-images.githubusercontent.com/44984207/50790448-97023c80-1284-11e9-8927-f650e3718ebf.png)

![image](https://user-images.githubusercontent.com/44984207/50790464-a3869500-1284-11e9-99f4-85f2e3aafe9e.png)

![image](https://user-images.githubusercontent.com/44984207/50790494-b4cfa180-1284-11e9-9900-91819898ed26.png)

![image](https://user-images.githubusercontent.com/44984207/50790564-d9c41480-1284-11e9-8b00-6b44b8093e29.png)

**Comment by vineethreddyramasa** [comment]
All Reports and Charts have "All" in filters

**Comment by jerrodanzalone** [comment]
I'm moving this to QA in Sprint 4. Please review @vineethreddyramasa if you have a chance.

**Comment by vineethreddyramasa** [comment]
Review Done. All the Reports and Charts have "All" in the filters

Test case Document: https://drive.google.com/open?id=1lMkGh4SWOI44avFMMsoZfSAIOCAYrznw
