### ISSUE TITLE
Project Report - Public Website

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#463]
When I (without logging in) click on Analytics, Reports, Projects - i get the following error:

![image](https://user-images.githubusercontent.com/44984207/50790675-36bfca80-1285-11e9-8d29-78675e96cbdd.png)

**Comment by jerrodanzalone** [comment]
This is a duplicate. It has been completed in Sprint 2.

![image](https://user-images.githubusercontent.com/41122083/52907853-a4212c80-322f-11e9-9015-be135a72735d.png)
