### ISSUE TITLE
Chart: Mission Area - Data Discrepancy

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#464]
The data in the Chart: Mission Area does not align with the Report Mission Area - Compare screenshots

![image](https://user-images.githubusercontent.com/44984207/50791055-4a1f6580-1286-11e9-884c-1e266c811505.png)

![image](https://user-images.githubusercontent.com/44984207/50791061-4ee41980-1286-11e9-94ff-b8847b3e568b.png)

Partners are completely unaligned - the chart shows 37. 68. 27. 31 5. 17 
Projects in Social Justice in the chart shows 60 v. 62 in the report.

**Comment by Ruthie2018** [comment]
QA passes 
https://docs.google.com/spreadsheets/d/1Vt_Qo3L7lr8-ic6lBniJXQjyjTfsjOOxsGX-JCaeebY/edit#gid=547627265

**Comment by Ruthie2018** [comment]
one improvement for a future ticket would be to put the categories in the same order in the reports and charts

**Comment by EdemD** [comment]
https://docs.google.com/spreadsheets/u/1/d/1Vt_Qo3L7lr8-ic6lBniJXQjyjTfsjOOxsGX-JCaeebY/edit?usp=drive_web&ouid=110830691228635827854
