### ISSUE TITLE
Chart: Mission Area

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#465]
Fix the title (Chart**:** Mission Area) of this report and move the legend so it does not block data - see screenshot

![image](https://user-images.githubusercontent.com/44984207/50791183-ae422980-1286-11e9-9013-96ac210cc31c.png)

**Comment by Ruthie2018** [comment]
remove the extra space after chart

**Comment by EdemD** [comment]
@shashankpatibandla as QA tester

**Comment by shashankpatibandla** [comment]
@EdemD tested this using a test script. You can find it in the sprint 4 folder
