### ISSUE TITLE
UI - Admin Control Text

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#467]
The admin should be able to change the text and links on the home page. 
![image](https://user-images.githubusercontent.com/44984207/50911815-47438280-13f6-11e9-9b08-30398dad994d.png)

**Comment by Keristiena** [comment]
Admin should also be able to control photos, colors of mission areas, and add mission areas.

**Comment by caadler** [comment]
This is being accomplished through the CMS.  Closing ticket.
