### ISSUE TITLE
Map Non-Responsive to Adding Partner

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#468]
After adding a community partner through through the admin side, the partner does not show up on any of the maps. The map should be responsive to new data and changes to data.

**Comment by Ruthie2018** [comment]
research ticket to manage updating GEOJson

**Comment by Ruthie2018** [comment]
related to #470

**Comment by caadler** [comment]
@EdemD  QA Testing complete.  Everything passes:
https://docs.google.com/spreadsheets/d/1MmQoFLcMfCKXGuXnxk2VfPqUdoTBGdd113NqpdMUy70/edit?usp=sharing
