### ISSUE TITLE
Drill-Through Functionality

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#471]
The maps should have drill through functionality.  Meaning the following:
If a user is looking at any community partner map, the user should be able to right-click the dot and drill-through to a list of the projects.

**Comment by Ruthie2018** [comment]
this is a research ticket to discover options of how to do this

**Comment by vbhat0891** [comment]
This functionality is working fine on the Legislative districts map, needs to be extended to the other maps.

**Comment by caadler** [comment]
@EdemD This has passed QA.  Test Plan document has been saved to Google Drive.
![image](https://user-images.githubusercontent.com/35402227/55499774-66743980-560c-11e9-8141-7127f884abc5.png)

**Comment by EdemD** [comment]
Thanks @caadler
