### ISSUE TITLE
Change Household Income Map to Community Partner Type Map

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#473]
Upon further review, the team does not believe the household income map is useful. Please change it in the following way:
- Remove household income data completely
- Have the legend based on Community Partner Type 
- Have the mission areas be a filter option. 

Rename the map 'Community Partner Type'

**Comment by Ruthie2018** [comment]
should be filtered by community partner type

**Comment by jerrodanzalone** [comment]
Please see ticket 737 for creating a Community Partner Type Report.
