### ISSUE TITLE
Data Definitions 

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#475]
Data definitions are an important aspect of understanding the reporting. Please allow for dimensions, visible in filters and in reporting to include data definitions. 

The data definitions will be provided by the admin and should be able to be changed by the admin through the admin console. 

The way this is requested is through a hover over. When a user hovers over definitions, a bubble with the data definition would display.

**Comment by EdemD** [comment]
@pallavi0902  assigned as QA
