### ISSUE TITLE
Project Map Visibility

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#477]
The project map should be only visible when users log into the application. Currently, it is a drop-down that is visible when users log into the application and not visible for the public (through a drop-down).

However, anyone with the project map URL can see the map regardless of whether they are or are not able to login. 

http://uno-cpi.herokuapp.com/projectmap

**Comment by jerrodanzalone** [comment]
Per discussions with the client, the Project Map should be visible to the public when not logged in. Move from behind login functionality and add-drop down option to maps when not logged in. The reason this was an issue is that most projects from the original data set do not have an address so are not shown on the map making the tool look less than impressive. This will change over time as new projects are added.

**Comment by jnabity** [comment]
@kalpanajha Sending back to development. This should be visible when user is not logged into the application per the updated feedback from client.
<img width="1682" alt="screen shot 2019-02-16 at 12 14 44 pm" src="https://user-images.githubusercontent.com/29965889/52903544-92666780-31e4-11e9-845b-8106ba219479.png">
FYI - @jerrodanzalone

**Comment by jnabity** [comment]
@kalpanajha & @jerrodanzalone this is ready for testing, correct? Looks like everything was resolved and a new pull request completed. However, I wanted to confirm it was ready for QA before moving to the QA pipeline.

**Comment by jerrodanzalone** [comment]
I wasn’t sure if I wanted to extend this ticket to the filters. Go ahead and move it down the pipeline and I’ll create a separate ticket for project filters.

**Comment by kalpanajha** [comment]
Ya Joseph this is ready to go!
