### ISSUE TITLE
Project Map Enhancements

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#478]
The project map should be enhanced in the following way:
Color code the project map by engagement type and add the following filters:
- Mission Areas
- Legislative Districts (already there but needs relabeling)
- Community Partners
- Campus Partners
- Academic Years
- Community Partner Types 

Each dot should have the following in the cover over:
- Name of the Project
- Projects mission area
- List all community partners
- List all the types of community partners
- List all the campus partners
- Academic Year

IF more projects occur on the same location and therefore are represented with one dot, the hover over should say:
"**x** number of projects have taken place in this location addressing [list all mission areas] mission area(s). For details on the projects and community partners, click here." 

From here the user should be able to drill through to a list of projects, community partners, etc. 

![image](https://user-images.githubusercontent.com/44984207/50913949-26316080-13fb-11e9-9d3c-2f155dc2a562.png)

**Comment by Ruthie2018** [comment]
#471 will address the drill through functionality piece

**Comment by jnabity** [comment]
@EdemD This is ready for testing. Please send back if you find anything not complete.

**Comment by EdemD** [comment]
Test document: https://drive.google.com/open?id=1Fc-noApzkPmGKauonO9QMSHAVIvhh2s8WpGXsO9WmBA
