### ISSUE TITLE
Register Campus Partner - Limiting Entries

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#479]
When filling out this campus partner form, there should be a control to ensure that nobody is registering a campus partner that is already listed. 

At this point, anyone can fill out this form and is able to submit the form for a campus partner that is already in the system. 

When a user starts typing a campus partner listed, it should prompt the user to confirm this campus partner rather than allowing the user to submit the form with an existing campus partner. 

![image](https://user-images.githubusercontent.com/44984207/50914842-1f0b5200-13fd-11e9-8b4d-bd126cc598bd.png)

**Comment by Keristiena** [comment]
Other requests:
-	Edit to table title to read “Register: A New Campus Partner”
-	Cell phones shouldn’t be required for the point of contact when registering a campus partner
-	Grays are inconsistent in buttons

Additional thoughts:
Avoiding duplicate campus partners being registered

When I start to type in an existing name of a campus partner nothing populates to show that this campus partner is already entered.

	For someone who is trying to enter in a campus partner that already exists there are possibilities that individual might use a different naming convention and create duplicate information, which is why this somehow still need to pull from what campus partners are already there. 

•	For example -  if I started to register the Barbara Weitz Community Engagement Center (which is already registered) as Weitz Community Engagement Center OR Community Engagement Center or event CEC it should show that this campus partner is already there and not allow me to submit the information, with a pop-up message telling the campus user to create a personal profile and associate this profile with the already existing campus partner.

**Comment by jerrodanzalone** [comment]
Moving this to sprint 5. Along with projects, we need to make find a way to better use validation when submitting forms

**Comment by EdemD** [comment]
@shashankpatibandla @ QA tester

**Comment by shashankpatibandla** [comment]
Test document - https://docs.google.com/spreadsheets/d/1LsngqCJK_cp2WXT11AeLwwwCm4zKmR5XU2c25BS7AmY/edit#gid=1719049306
