### ISSUE TITLE
Register Campus Partners - Confirmation

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#480]
When i fill out this form, i receive no confirmation or notice that the form was submitted. as a user, i don't know if it went through or something went wrong.

**Comment by Ruthie2018** [comment]
When I register a campus partner, I do get a confirmation text.

![screen shot 2015-06-10 at 1 28 22 pm](https://user-images.githubusercontent.com/35461326/52234435-45e76780-2887-11e9-9b58-4ce3df3963ee.png)

**Comment by Ruthie2018** [comment]
![image](https://user-images.githubusercontent.com/35461326/52234471-5bf52800-2887-11e9-8288-5c0e6d5da7d9.png)

**Comment by caadler** [comment]
@Ruthie2018  Per Sprint 1 feedback from Client, change verbiage to: Your organization is successfully registered as a campus partner.
