### ISSUE TITLE
Search Functionality in Admin Console

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#483]
The search functionality in the admin console does not work. I get the following errors:
**Please note - screenshots are just examples - this happens in every search box**

![image](https://user-images.githubusercontent.com/44984207/50915489-88d82b80-13fe-11e9-88a1-ef248b1b5656.png)

![image](https://user-images.githubusercontent.com/44984207/50915516-9392c080-13fe-11e9-9dac-b397e3ae5f6e.png)

**Comment by EdemD** [comment]
@shashankpatibandla as QA tester

**Comment by shashankpatibandla** [comment]
Tested and everything looks good. https://docs.google.com/spreadsheets/d/1vQEGkWGW7LPmlKNI9gBQUjUNJj1xPGYTFnk_bEBvayo/edit#gid=1608651010
