### ISSUE TITLE
Campus Partner Registration

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#484]
The community partner registration form does not work. The data entered into this form is not visible in the admin tables or in the reporting. 

![image](https://user-images.githubusercontent.com/44984207/50917723-e8850580-1403-11e9-8e1c-272932c0a7d4.png)

**Comment by vbhat0891** [comment]
Contact User Model had an email field, which was changed to unique=False, to fix this issue.

**Comment by EdemD** [comment]
Pallavi please work on testing #484. Thanks
