### ISSUE TITLE
Admin Navigation 

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#487]
1) If i click on a map after logging in as an admin, the navigation bar no longer works. It does not react to the mouse. This bug should be fixed.
![image](https://user-images.githubusercontent.com/44984207/50918589-46b2e800-1406-11e9-8520-27e2272cdae6.png)

2) The admin should also be able to view /interact with the project drop-down. This is only visible to campus users after logging into the application. the admin should see everything that campus users see, and have additional functionality as an admin.

![image](https://user-images.githubusercontent.com/44984207/50918688-8e397400-1406-11e9-8085-0acfd63aea26.png)

**Comment by Ruthie2018** [comment]
maps do not work at all in IE

**Comment by jerrodanzalone** [comment]
There's a separate ticket for mobile/browser compatibility. This is for the admin navbar, which currently works.
