### ISSUE TITLE
Context needs to be provided for the campus partner user registration

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#488]
Currently, to register as a campus partner - users have to go to the 'login' and click on Campus Partner User Signup. 

![image](https://user-images.githubusercontent.com/44984207/50918847-eec8b100-1406-11e9-9882-58ada152424a.png)

There is no context or explanation to this. We should provide some additional explanation which also includes information on the Register Campus Partner form since a campus partner needs to be created before a campus user can be assigned.  

I am also unclear about how this connects to the "point of contact information" in the Register Campus Partner form. Since the Register Campus Partner form is not working, i am unable to test this. 

![image](https://user-images.githubusercontent.com/44984207/50919659-05700780-1409-11e9-84a0-9506aca31719.png)

![image](https://user-images.githubusercontent.com/44984207/50919633-f38e6480-1408-11e9-83ac-eca231f2e6a6.png)

**Comment by vineethreddyramasa** [comment]
![screenshot 2019-02-25 17 38 11](https://user-images.githubusercontent.com/35588146/53376544-4de57500-3924-11e9-9f26-067a5e8a0ac2.png)

Q/A done.. Page works as expected and all links are working.
