### ISSUE TITLE
Forgot Password 

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#489]
This feature is not working. If you fill it out and submit your new password request, you get the following error:
![image](https://user-images.githubusercontent.com/44984207/50919785-60096380-1409-11e9-842a-73fcdd3e34b2.png)

![image](https://user-images.githubusercontent.com/44984207/50919777-58e25580-1409-11e9-9300-2b74c65f4b1e.png)

**Comment by Jantz021991** [comment]
Email configuration is implemented using EmailGun, we will receive an email from Webmaster -

![image](https://user-images.githubusercontent.com/26983295/55294474-0db45f00-53c8-11e9-9bf3-60ad3a0d646a.png)

Here is the content of email -

![image](https://user-images.githubusercontent.com/26983295/55294484-2d4b8780-53c8-11e9-88c4-024bd093ba0f.png)

**Comment by EdemD** [comment]
@caadler as QA tester

**Comment by caadler** [comment]
@Jantz021991 The first line in the email content needs to be updated to:  
To initiate the password reset process for your username (USERNAME0) in UNO CPI application, please use the link below:

Currently it is:
To initiate the password reset process for your Username -caadler@unomaha.edu , in UNO CPI application,please use the link below:

"username" should not be capitalized, the individual's username should be in parentheses without commas, and there needs to be a space before the word "please"

**Comment by Jantz021991** [comment]
@caadler , I have made the changes as suggested.

**Comment by caadler** [comment]
@Jantz021991 There are still issues with the first sentence in the email content.  It should say:

To initiate the password reset process for your username (caadler@unomaha.edu) in the UNO CPI application, please use the link below:
