### ISSUE TITLE
Admin Table - Community Partner 

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#490]
When i add a community partner through the admin console it does not impact any type of reporting. 

Emphasized partner was wadded through the admin table. 
![image](https://user-images.githubusercontent.com/44984207/50920074-0eada400-140a-11e9-9f86-c8d5e171c9c8.png)

**Comment by caadler** [comment]
@vbhat0891 Per discussion with Keristiena, the projects are showing on reports, but not on maps.  This ticket should be moved to Sprint 3 or 4 for Maps.

**Comment by Keristiena** [comment]
I do not know if the projects are showing up on all reports, but they did on some for sure.

Keristiena S. Dodge
Project Specialist
Office of Academic Affairs | EAB 202
University of Nebraska at Omaha | www.unomaha.edu

402.554.2364
kshenouda@unomaha.edu

[Media:UniversityCommunications:Graphic Design:Brand tools:Logos- UNO:Vector files:Lock-up:Lockup-color on white backgrnd.eps]

**Comment by Ruthie2018** [comment]
see also #468, #470, #514, #515

**Comment by vbhat0891** [comment]
The GeoJSON scheduler is up and running, go ahead and test. This is scheduled to run once a day for now. If needed, we can change the run interval to facilitate testing.

**Comment by vbhat0891** [comment]
This will work as expected if all the associations in other tables like Community Partner missions are provided with an appropriate value.

**Comment by EdemD** [comment]
Test document: https://drive.google.com/open?id=18-igWFFwODvniSLXcagOhZsqLxtKJZN2e0eV0yiuU_s
