### ISSUE TITLE
MAP - Community Partner Search Functionality 

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#492]
The search functionality in the map does not work. After adding a partner by the name of Keristiena's Test Community Partner, i cannot find this partner by searching Test

The search functionality should be based on part of the title and not the start of the title.  In other words: If i want to search for Keristiena's Test Community Partner, i should not have to start the search with Keristiena. 

![image](https://user-images.githubusercontent.com/44984207/50920406-ef634680-140a-11e9-9459-a719e2209b8b.png)

**Comment by Keristiena** [comment]
The ‘Search Community Partner’ box only worked sporadically. For example, when I typed in ‘Fontenelle,’ two options popped up (Fontenelle Elementary, Fontenelle Forest). But when I typed in ‘Senior Companions,’ everything single community partner. Not sure if this is just a data issue, or a functionality issue.

**Comment by caadler** [comment]
@vbhat0891 The search functionality works for the points on the screen, but it does not change the partner count at the top.  When changing a filter, the partner count adjusts, but the search does not update this.

**Comment by jnabity** [comment]
@caadler take another look to confirm this is still working.

**Comment by caadler** [comment]
@jnabity @EdemD  This is tested on Community Partner map, legislative district, community partner type maps, and they all worked as expected.  The Project Map didn't load in the STA site, so I couldn't test that.

**Comment by EdemD** [comment]
https://drive.google.com/open?id=1O81VlPrw_m7zfcrm78GZqaK4C6p5Y2GHX0afZlqEA8k

**Comment by caadler** [comment]
@EdemD Project map is working now.  Search functionality works as expected.
