### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#494]
When i fill out a create a project form, the project status asks if the project is active of completed. I don't necessarily have a solution, but i am wondering how we can prevent the following situation from occurring -

User enters project while it is ongoing, it is entered as an active project, and the user forgets to go in to change the status to completed. 
- How do we prevent this?
- What is the impact of this?

**Comment by jnabity** [comment]
This is a duplicate of #836. Closing.
