### ISSUE TITLE
Mission Tye

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#496]
Map reporting is based on the primary mission area. What is the impact of adding additional mission areas. Does this impact the other reports?  Ideally, it would.

**Comment by Keristiena** [comment]
![image](https://user-images.githubusercontent.com/44984207/50921285-41a56700-140d-11e9-8248-ca4f64ff5661.png)

**Comment by caadler** [comment]
Per request from Keristiena (logged in #914 ) all reports will use primary mission area. Closing ticket.
