### ISSUE TITLE
Project Form: Remove and Change Fields

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#497]
Remove the following fields in the Project Form:
- Campus Partner block - Hours and Volunteers
- Facilitator

![image](https://user-images.githubusercontent.com/44984207/50926060-b5e60780-1419-11e9-8b97-3cefb1e92fd2.png)

Make the following fields non-mandatory:
Description 

![image](https://user-images.githubusercontent.com/44984207/50926072-bf6f6f80-1419-11e9-94d3-88bc567503e1.png)

**Comment by vineethreddyramasa** [comment]
![image](https://user-images.githubusercontent.com/35588146/51815818-17ff9300-2289-11e9-9b8e-f5de7e5aebbb.png)

Removed Hours, Volunteers, Facilitator fields. Made the Description field Non-Mandatory.

**Comment by EdemD** [comment]
Screenshot of : ![497](https://user-images.githubusercontent.com/19415394/52219340-0fe3bc80-2862-11e9-9155-421c57810c9c.png)
Remove the following fields in the Project Form:
* Campus Partner block - Hours and Volunteers
* Facilitator
