### ISSUE TITLE
Add More options in Forms (form functionality)

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#500]
When you submit a form, whether it is registering a community/campus partner, or creating a project - when you add "Add More" contacts/mission/partners, there is no way to go back and delete that extra line. If you click on this button accidentally, there should be a 'remove' option. 

Project Form example:
![image](https://user-images.githubusercontent.com/44984207/50926815-8df7a380-141b-11e9-84bc-6e3c644dd737.png)

**Comment by caadler** [comment]
@vineethreddyramasa  I don't believe this is working properly on the Create Project form.  I can delete multiple "Mission" rows (functionality is a bit weird, but it works), but I cannot delete extra Community Partner or Campus Partner rows.

**Comment by vineethreddyramasa** [comment]
![image](https://user-images.githubusercontent.com/35588146/52184649-8d181e80-27db-11e9-8adb-ed933751996f.png)

**Comment by jnabity** [comment]
@caadler is meeting with the client to discuss options for this ticket. Based on the current coding the forms are working correctly (Create Project, Register Campus Partner, Register Community Partner). Once we have confirmation from Craig and client on next steps we can proceed.
[Form Remove Functionality.docx](https://github.com/uno-isqa-8950/uno-cpi/files/2848062/Form.Remove.Functionality.docx)
