### ISSUE TITLE
Creation of duplicate projects

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#503]
Within the Create Project screen, users should not be able to add projects that are the same. I understand that technically they could go to 'all projects' and search the projects before adding, but in practice - i think we need to come up with a way that users are prompted with the existence of projects with similar names  so we can avoid duplication.

**Comment by EdemD** [comment]
@duwaezuoke as QA tester

**Comment by jerrodanzalone** [comment]
@duwaezuoke Please test current functionality at uno-cpi-sta.herokuapp.com/checkProject

**Comment by Ruthie2018** [comment]
change to dropdown that is selectable if project is found

**Comment by vbhat0891** [comment]
The comment above is misleading, this was moved to In progress to change the block of text we had earlier to a drop down
![image](https://user-images.githubusercontent.com/26983338/56465348-4ccf4200-63c1-11e9-801f-1a7cc3b5ca8a.png)

We were waiting for Keristiena to come back on this, it is now changed to this as per her feedback-
![image](https://user-images.githubusercontent.com/26983338/56465366-87d17580-63c1-11e9-8ea5-255678b17904.png)

**Comment by duwaezuoke** [comment]
QA tested and confirmed done-done. Reference: https://drive.google.com/open?id=1hA7MHrj4EcOAySb-w8W20ix0ioj9znQGaQURXEDxCvs
