### ISSUE TITLE
Map Roads

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#505]
The roads (in white) on the map background are a bit difficult to see. 

![image](https://user-images.githubusercontent.com/44984207/50927541-b2ed1600-141d-11e9-92e2-e390ab91bcc7.png)

**Comment by EdemD** [comment]
@pallavi0902   assigned as QA

**Comment by Ruthie2018** [comment]
closing this is handled by Google maps API
