### ISSUE TITLE
Mission Area Map View

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#506]
I see that I can isolate the different mission areas, or I can view them all at once. I’m wondering if there’s a way so that I can view two areas at once (e.g., environmental stewardship and health & wellness) but not the others, or to slowly remove areas one at a time, rather than the ‘all’ or ‘one’ option. It’s not a priority, but as I went through to select the options I felt like it would be helpful to look at more than one area at a time. 

![image](https://user-images.githubusercontent.com/44984207/50927594-dfa12d80-141d-11e9-8e7f-8e2ae526202c.png)

**Comment by jerrodanzalone** [comment]
Not achievable this semester.
