### ISSUE TITLE
Community Partner Report

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#507]
When i'm logged in as a campus user, the community partner report does not work and provides this error:

![image](https://user-images.githubusercontent.com/44984207/50927800-7e2d8e80-141e-11e9-9ab2-a1394f6cf544.png)

**Comment by Keristiena** [comment]
Same is true for the Project Report: 
![image](https://user-images.githubusercontent.com/44984207/50927850-9d2c2080-141e-11e9-9437-bdc1f7de3cad.png)

**Comment by Ruthie2018** [comment]
this ticket needs to check all reports are working

**Comment by jerrodanzalone** [comment]
![image](https://user-images.githubusercontent.com/41122083/52385088-be942280-2a45-11e9-9e20-215786bb0a80.png)

**Comment by jerrodanzalone** [comment]
Also, project report: 
![image](https://user-images.githubusercontent.com/41122083/52385127-e6838600-2a45-11e9-8ffa-1b78663e14b4.png)

**Comment by jerrodanzalone** [comment]
And project reports when not logged in: 
![image](https://user-images.githubusercontent.com/41122083/52385157-0adf6280-2a46-11e9-8054-0b92473fe0db.png)
