### ISSUE TITLE
Project Status - Add Discontinued Option

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#508]
Add a Discontinued variable in the project status. 
![image](https://user-images.githubusercontent.com/44984207/50927920-cb116500-141e-11e9-82eb-0cd966ad224c.png)

**Comment by caadler** [comment]
@jerrodanzalone  I was looking at this ticket.  These values come from a setup table in the admin panel under Projects.  Keristiena just needs to add a third option.  We can confirm with her and close this ticket.
