### ISSUE TITLE
Contact Us

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#509]
The contact us form does not work. When i submit a contact form, i get the following error:
![image](https://user-images.githubusercontent.com/44984207/50928072-38bd9100-141f-11e9-98d9-c0b3b4cc5c19.png)

**Comment by caadler** [comment]
Possibly related to #489

**Comment by Jantz021991** [comment]
@caadler - Do you have the email to whom the queries in contact us page needs to be redirected to?

**Comment by Jantz021991** [comment]
and a subject line that needs to be given for emails coming from the contact us page.

As of now - this is the subject line **CPI Contact Form submission**

**Comment by EdemD** [comment]
@duwaezuoke as QA tester

**Comment by EdemD** [comment]
The Contact Us page is being removed. The footer now has the email.
