### ISSUE TITLE
Consistency

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#510]
Organization information should be consistent. One user is seeing this:

![image](https://user-images.githubusercontent.com/44984207/50928379-209a4180-1420-11e9-940b-57e68faf16da.png)

Another user is seeing this:

![image](https://user-images.githubusercontent.com/44984207/50928426-40ca0080-1420-11e9-858b-06ae61712846.png)

Also note: should be 'contact information', not 'contacts information'.

**Comment by Ruthie2018** [comment]
closed because work completed in #552
