### ISSUE TITLE
Community Partner Active/Inactive Flag 

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#512]
Community Partner Active/Inactive Flag must be implemented in the system. A Community Partner must be made active when they are tagged to a project and inactive when they are not.

**Comment by EdemD** [comment]
@kalpanajha  assigned as QA

**Comment by jnabity** [comment]
Adding scheduler to execute query during Sprint 4.

**Comment by EdemD** [comment]
@kalpanajha as QA tester

**Comment by kalpanajha** [comment]
Community partner active/inactive flag

https://drive.google.com/open?id=1rnWKtNhnu94gLRyKt1JVRYoFq5H5sCM5
