### ISSUE TITLE
Reports/Maps are not responsive to mission area changes

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#514]
If the admin changes the mission area of existing community partners, it does not impact/change the reports/maps. This error should be fixed.

**Comment by caadler** [comment]
Separating into multiple tickets, one for each functional area.

**Comment by Ruthie2018** [comment]
similar issues as #468 #470 and #515

**Comment by EdemD** [comment]
@pallavi0902  assigned as QA

**Comment by jerrodanzalone** [comment]
Please evaluate based on just the reports. There are multiple separate tickets for maps. Thanks.

**Comment by pallavi0902** [comment]
QA ticket passed. https://drive.google.com/file/d/1laqISQrpC6XaYywxgoXydzWeEHGuCdWt/view?usp=sharing
