### ISSUE TITLE
Number of Projects in Maps

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#515]
When a project is added, the community partner pop-up box field “number of Projects” in maps won’t change. This error should be fixed.

**Comment by Ruthie2018** [comment]
same issue to #468

**Comment by EdemD** [comment]
@vineethreddyramasa assigned as QA.

**Comment by EdemD** [comment]
@shashankpatibandla as QA tester

**Comment by shashankpatibandla** [comment]
Passed. test document - https://docs.google.com/spreadsheets/d/1W4L89SBJNWQJow-gi0Odr3ZvQqe2NSUSY3oo3s3yU3o/edit#gid=1361726414
