### ISSUE TITLE
GENERAL FIXES TO THESE TABLES

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#518]
r-Need text that defines each column/field (hovering over engagement type for example)
-Semester should be a drop down
-Display names are not correct and inconsistent throughout tables: Here are a list of the column display names and in order:
	Project Name
	Mission Area
	Community Partner
	Campus Partner
	Engagement Type
	Academic Year
	Semester
	Status
	Start Date  (This information seems unnecessary for the table columns. It really should live near the end date in the data that expands below the project.)

![image](https://user-images.githubusercontent.com/44984207/50931232-a1a90700-1427-11e9-8801-fba9235baceb.png)

-	Expandable display names of project tables should be updated in the following order AND terms:
	Secondary Mission Areas
	Start Date
	End Date
	Number of UNO Students
	Number of UNO Students Hours
	Number of UNO Faculty/Staff
	Number of K-12 Students
	Number of K-12 Students Hours
	Number of Other Participants
	Activity Type
	Campus Facilitator 
	Description

**Comment by caadler** [comment]
Hover definition is on #475.  This ticket will be for consistent display names.

**Comment by duwaezuoke** [comment]
![screenshot 271](https://user-images.githubusercontent.com/31281458/52511204-967efd80-2bc4-11e9-8dbf-bf82be5a84bb.png)

**Comment by duwaezuoke** [comment]
![screenshot 269](https://user-images.githubusercontent.com/31281458/52511791-510fff80-2bc7-11e9-98aa-7ce6727a60d8.png)

QA Test passed.

**Comment by duwaezuoke** [comment]
All requirements from the ticket has been met. 
![screenshot 272](https://user-images.githubusercontent.com/31281458/52513017-a222f200-2bcd-11e9-8aa6-2c902e600145.png)
Reference to drive: https://drive.google.com/open?id=1uW2P-UgEm7EKNpb_Y11Wzt1kvxc1Ilvr
