### ISSUE TITLE
Calendar Feature in Project Form

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#519]
r-There is an odd thing happening with the calendar feature within the start and end date – really this should just a be a calendar pop up not the arrows that go up and down for the year.
![image](https://user-images.githubusercontent.com/44984207/50931301-ce5d1e80-1427-11e9-8692-c4339c65f53c.png)

**Comment by caadler** [comment]
This has been resolved.  Closing ticket.
