### ISSUE TITLE
CEC data discrepancy 

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#522]
Some of the projects that have the CEC as a campus partner are not showing up in the “My Projects” table but they show up in the “All Projects” table.

@robynlloos  Can you provide examples?

**Comment by robynlloos** [comment]
I am trying to provide an example of this issue but when I am logged into the CPI tool as a campus user and I click on the All Projects table I get an application error. 
![all projects-application error-screen shot](https://user-images.githubusercontent.com/44984230/51131665-01bbf680-17f6-11e9-95f6-68d078e5b04b.JPG)
