### ISSUE TITLE
Project Table Lay-out

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#523]
When I change the project table to show 100 entries the table looks odd:	

![image](https://user-images.githubusercontent.com/44984207/50931631-d23d7080-1428-11e9-8403-891b33d10af5.png)

**Comment by EdemD** [comment]
Test document: https://docs.google.com/spreadsheets/d/17t9PMdaPZ9XeiCKjnleT_nRckz9yDXJjk8OEOqPBjXU/edit?usp=sharing
