### ISSUE TITLE
Project Form: Partners

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#526]
In addition to being able to add multiple campus and community partner (see additional ZenHub ticket), we want the partner questions to appear right by each other. Right now, the project form asks for a campus partner, and you have to scroll all the way down to enter campus partners.

**Comment by Keristiena** [comment]
In addition, end users want to be able to enter in new partners if the partners are not already registered. Discussed 1/18/2019 with team.

**Comment by caadler** [comment]
@Ruthie2018 I believe this should be a Sprint 1 ticket with the other Project Form labels.

**Comment by Jantz021991** [comment]
per discussion with client 1.28.19, functionality will remain as is. this ticket will focus on reorganizing the form portion of this ticket only.

**Comment by caadler** [comment]
@shashankpatibandla I believe these questions should be moved to the top of the form, instead of the bottom.  I'll confirm with the clients tomorrow.

**Comment by jnabity** [comment]
@shashankpatibandla per discussion and Craig's comments, please update the form to move Community Partner and Campus Partner details to the top of the Create Project Form.

**Comment by shashankpatibandla** [comment]
@jnabity I fixed this and pushed it along with merge request #630. As soon as jerrod accepts the merge request you can go ahead and test it. To confirm I moved the Partner questions to be on the top

**Comment by jnabity** [comment]
@shashankpatibandla I have tested this issue and it passes. The Campus Partner and Community Partner details are now located toward the top section of the project form.

**Test Script**
https://docs.google.com/spreadsheets/d/17aOzs13He8EjoLrF1VKPrY7jRlvWByq0cq-6wUHXfPw/edit#gid=1427435639
<img width="1792" alt="community_partner_fields" src="https://user-images.githubusercontent.com/29965889/52522490-b0afee80-2c4b-11e9-8b37-d19143cda683.png">
<img width="1792" alt="campus_partner_fields" src="https://user-images.githubusercontent.com/29965889/52522491-b0afee80-2c4b-11e9-9e9a-2345f29877e0.png">

CC: @jerrodanzalone @EdemD
