### ISSUE TITLE
General fixes to all maps- map info window

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#527]
o	Edit “Community Type” to read “Community Partner Type”

o	Edit “Number of project” to read “Number of Projects” - Some pop-up boxes show the number of projects and others don’t – I assume those that do NOT show number of projects are because that specific partner (within the community partner map) is a partner but hasn’t had projects associated with a specific campus partner yet – please confirm. 

o	Remove county from the pop-up

o	Remove brackets and quotation marks around text

![image](https://user-images.githubusercontent.com/44984207/50932096-31e84b80-142a-11e9-80c9-fa1cd4b84568.png)

**It is very difficult to select the different dots within one mission area because they all appear to be one dot – it would be much more user friendly if the dots had different transparencies so that you could see which partner was which on the map (see original map created on UNO website)**

![image](https://user-images.githubusercontent.com/44984207/50932155-5e9c6300-142a-11e9-9fc3-a7e532c586b0.png)

In the MAP filter:

o	Edit “All Community Types” to “All Community Partner Types”
o	Edit “All District” to “All Legislative Districts” - Move legislative district filter lower. 

Name of the Maps -
- Edit map title  “Maps: Community Partner” to read “Maps: Community Partners”
- Edit map title from “Maps: Legislative District” to read “Maps: Legislative Districts”
- Edit “Maps: Community Projects” to “Maps: Projects”

**Comment by robynlloos** [comment]
Additionally, some of the pop-up boxes that show on the maps are showing a community partner listed as a weird number, not the name of the community partner organization. This could be a result of the data entered but either way should clarify why this is the case:
![pop-up boxes-community partners as numbers-screen shot](https://user-images.githubusercontent.com/44984230/51132924-2fef0580-17f9-11e9-97bc-e2fad383ddfb.png)

**Comment by robynlloos** [comment]
Gray navigation bars on maps look inconsistent and not very great in terms of visibility/accessibility as many people will look at these. For instance, comparing the 2 screenshots below show the inconsistencies.
![community projects map-gray nav and filter bars-screen shot](https://user-images.githubusercontent.com/44984230/51133716-59a92c00-17fb-11e9-9075-21ab14c69785.JPG)
![household income map-gray nav and filter bars-screen shot](https://user-images.githubusercontent.com/44984230/51133717-59a92c00-17fb-11e9-8ae7-345fa6a499f1.JPG)

Additional changes should be made to this navigation bar to make it easy to read (i.e., removing second gray box that is shown behind the title of the map, making the red line above the gray nav bar on the maps white (and making this consistent throughout), text size, bolding etc.

**Comment by caadler** [comment]
Breaking into smaller tickets. Labels changes earlier, map functionality.

**Comment by EdemD** [comment]
@kalpanajha Assigned as QA

**Comment by jnabity** [comment]
@kalpanajha please proceed with testing and send back to Dev with any thing that stick out as incomplete.

**Comment by kalpanajha** [comment]
General fixes to maps that are still remaining.

https://drive.google.com/open?id=1GlKLOoCzmrBKMdjdIY2J3-Daf_NlQB6t

**Comment by vbhat0891** [comment]
Hey, @kalpanajha can you comment here what is pending in this ticket? I don't have access to the document you have shared. Also, this was not assigned to me so I had no clue about it although I was working on fixing all the issues.

**Comment by kalpanajha** [comment]
Hey Vivek, I have shared you the link for the document. However, I am copy
pasting it in the email as well. I will check it again and will let you
know if anything is missing.

Ticket #527

General fixes to maps

Maps: Community Partners

   -

   “Community Type” needs to be changed to “Community Partner Type” in the
   pop-ups
   -

   “County” needs to be removed from the pop-ups.



   -

   In Filters


   -

   Change “All Community Types” to “All Community Partner Types”.
   -

   “All Legislative Districts” filter needs to be moved lower

Maps: Legislative Districts

   -

   Need to edit Map title from “Maps: Legislative District” to “Maps:
   Legislative Districts”.
   -

   “Community Type” needs to be changed to “Community Partner Type” in the
   pop-ups



   -

   In Filters


   -

   Change “All Community Types” to “All Community Partner Types”.
   -

   “All Legislative Districts” filter needs to be moved lower


Maps: Community Partner Type

   -

   “Community Type” needs to be changed to “Community Partner Type” in the
   pop-ups

Maps: Projects

The map is down right now so can’t test it.

   -

   filters
   -

      “All College” to “All Colleges”




Thanks,
Kalpana Jha

**Comment by caadler** [comment]
@vbhat0891 Please rename college filter to "All Colleges and Main Units".

**Comment by vbhat0891** [comment]
@caadler This is done. @kalpanajha Please check for this as well when you are testing this ticket.

**Comment by vbhat0891** [comment]
@kalpanajha I have addressed the issues, I would prefer to leave the legislative district filter on top because it is the "Legislative Districts map". Let me know if you think otherwise, we can discuss with the team on Wednesday about this.
![image](https://user-images.githubusercontent.com/26983338/55769937-210a9e80-5a48-11e9-907c-5dab5ec49e75.png)

**Comment by kalpanajha** [comment]
General fixes to maps tested

https://drive.google.com/open?id=1LWWbPVU4NjzNWPZjCp8c2cX2wTjvDdvH
