### ISSUE TITLE
General + Label Feedback for All Charts

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#529]
-	Edit “Mission Area” to “Mission Areas”
-	Edit “Engagement Type” to “Engagement Types”
-	Make the in-report titles consistent with the drop down edits mentioned in other tickets. 
-	Grays appear to be inconsistent within the individual charts
-	Edit “Engagement Type” to read “Engagement Types”
-	Edit “Community Type” to read “Community Partner Type”
-	Edit “Academic Year” to read “Academic Years”
-	Footer looks odd on the charts
-	Boxes for each chart that show the color codes are inconsistent in placement and look

**Comment by Ruthie2018** [comment]
all work on this ticket has been completed in #528 except for inconsistent grays, footer, and boxes for color codes

**Comment by kalpanajha** [comment]
general fixes for charts

https://drive.google.com/open?id=1sphgat6QEQspE2P71EpvRrSkE7Yw5X0u
