### ISSUE TITLE
CRUD for Organizations

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#530]
Fonts on all tables under the individual campus user are not consistent with others throughout tool (in both the view and edit for the organization profile)

I am unable to edit the organizational profile that I am associated with as the campus user

I am unable to edit what campus partner name I am associated with under my profile

Grays are inconsistent on organizational chart 

Missing other organizational fields “Department” – pending the specific way we need to name this for the campus partner drop down list as we move forward

When I go to enter in a contact for the organization it requires a cell phone number
o	Cell phones should NOT be required for any UNO contacts – only UNO office numbers
o	There should be indicators that show you what information is required like the rest of the areas you enter information 

![image](https://user-images.githubusercontent.com/44984207/50933080-7c6ac780-142c-11e9-91b1-3e069d12eac3.png)

**Comment by caadler** [comment]
Splitting into multiple tickets.  Issues editing and fonts/coloring.

**Comment by shashankpatibandla** [comment]
This Ticket will only be for "EDIT" and "DELETE" functionality of organizations page. #624 tackles with "ADD"  functionality of organizations page and #552 tackles with inconsistencies regarding the text and format
