### ISSUE TITLE
Update Messages

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#531]
Update messages look very odd – those and the thank you boxes should be consistent across the board or at least in where and what they look like for those on the same page versus those on a new page

![image](https://user-images.githubusercontent.com/44984207/50933692-a7edb200-142c-11e9-93c2-dd8b55fc53db.png)

**Comment by jerrodanzalone** [comment]
These are part of the django defaults. It's possible to override but takes time. Not a priority at this point.
