### ISSUE TITLE
Update Footer

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#532]
Footer looks odd throughout tool on most pages. 

@robynlloos 

Robyn, could you provide a little bit more info here. I have these sentences in your feedback too, but that's all: "The footer doesn’t sit at the bottom of the page as it should" and "Footer looks odd on the charts"

**Comment by robynlloos** [comment]
![footer view issue-screen shot](https://user-images.githubusercontent.com/44984230/51131719-1f895b80-17f6-11e9-8e79-579a20e0007d.JPG)
![home view issue-browser display-screen shot](https://user-images.githubusercontent.com/44984230/51131734-24e6a600-17f6-11e9-8094-dc7eb7192b14.JPG)

**Comment by robynlloos** [comment]
Additionally, I noticed that when I make the overall size of the window of my browser smaller the images that show on the home p
![home view issue-browser display-screen shot](https://user-images.githubusercontent.com/44984230/51131881-80b12f00-17f6-11e9-821d-038e67a1131a.JPG)
age do not size accordingly. For example:

**Comment by jerrodanzalone** [comment]
After footer is fixed, client has requested to be able to edit discrimination in CMS. I will update this.

**Comment by EdemD** [comment]
Test document: https://drive.google.com/open?id=1pPfbykaJRVcPCbKm4t_CrSSHzUg9DhPWKplgCV6N9nA
