### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#533]
We may want to think about ways to make the home page more  appealing. Few ideas previously discussed:
- Text overlay on the images
- Images should link directly to the relevant maps. 

Sample websites for UI enhancement 
•	https://www.p4k.org/
•	https://www.wipro.com/

**Comment by robynlloos** [comment]
**Changes to the Home Page of the CPI tool**

**- A mock-up of the home page, the images, and the text will all be provided by sprint 2 or 3.** This will include a secondary page that features examples of the 6 issues areas - which we will provide the content for in the mock-up.
- These changes will create a clearer understanding of what the tool is and how it relates to UNO
- Changes will exclude having interactive maps
- Changes will include one page with examples of what the mission areas
- Changes will reflect a more modern home page look consistent with UNO’s branding and accessibility efforts
