### ISSUE TITLE
Admin Mass Export

### ISSUE THREAD

**Issue by Keristiena** [uno-isqa-8950/uno-cpi#534]
The admin was supposed to have the ability to do a mass data dump into excel. How do i do this?

**Comment by EdemD** [comment]
@shashankpatibandla  assigned as QA.

**Comment by EdemD** [comment]
https://docs.google.com/spreadsheets/d/1Lr5Ld5Byj8jYp3DWtFZb2SrdqMdEuhTqwCzyHg1c--A/edit#gid=16484329
