### ISSUE TITLE
Forms need to be consistent throughout the tool

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#547]
o	Fix form headers same gray color (will be based on the gray color that UCOMM provides)
o	Fix form headings and other text size and weight/thickness equal throughout (the heading text used throughout the forms is currently too large – make smaller)
o	Fix form edges the same (Will be based on the edge of the button example that UCOMM will provide)
o	Fix button effects the same (all drop shadow effects be removed)
o	Use consistent singular/plural language within the form headings and all other text (refer to official display names provided)

**Comment by caadler** [comment]
These have been fixed.  Any future issues will be logged under separate tickets.
