### ISSUE TITLE
Error/thank you/system generated messages (i.e., thank you box, log-in box etc.)

### ISSUE THREAD

**Issue by robynlloos** [uno-isqa-8950/uno-cpi#551]
o	Make all error messages consistent and aligned properly on the website page
o	Make all thank you messages consistent in color and style as specified above
o	Make all user and organizational profile boxes/forms consistent with the changes specified above
o	May change the red header line to reflect different color for accessibility reasons

**Comment by jerrodanzalone** [comment]
Repurposing this to make error messages red and consistent across the board: 

![image](https://user-images.githubusercontent.com/41122083/52537764-c565b280-2d2f-11e9-96cb-0783e0c6d9d0.png)

**Comment by duwaezuoke** [comment]
QA testing and review completed and confirmed done done.
Reference to drive: https://drive.google.com/open?id=18pq5uJX0vRTX301PZuOZHkg8eQA6GGaa
