### ISSUE TITLE
Address ordering

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#559]
In general order the address information to be consistent with other address entry fields

**Comment by shashankpatibandla** [comment]
General flow of address

•	Physical Address
•	City
•	State
•	Zip
•	Country

**Comment by jnabity** [comment]
I have tested the Project Create Form and the Register Community Partner Form.
@Jantz021991 were there any other forms updated for this address alignment request that need tested?

<img width="861" alt="screen shot 2019-02-02 at 9 02 30 am" src="https://user-images.githubusercontent.com/29965889/52165679-771a3900-26c9-11e9-8323-a4aed79e1d87.png">
<img width="1169" alt="screen shot 2019-02-02 at 9 01 17 am" src="https://user-images.githubusercontent.com/29965889/52165680-771a3900-26c9-11e9-96a2-786cdbae0454.png">

**Comment by jnabity** [comment]
@Jantz021991 can you please update the Organization Profile screen below for the address field order?

<img width="1792" alt="screen shot 2019-02-02 at 12 32 19 pm" src="https://user-images.githubusercontent.com/29965889/52167813-adb27c80-26e6-11e9-8190-4fce9fae2526.png">

FYI - @EdemD  @jerrodanzalone  @caadler

**Comment by jnabity** [comment]
@Jantz021991 The update to the organization profile looks great. However, in looking through the screens, I found that going into a project to edit the project has a different order for the address fields. Is that something we can resolve in this ticket as well? The excel sheet will show steps to get to the edit screens.

<img width="1792" alt="screen shot 2019-02-03 at 9 45 58 am" src="https://user-images.githubusercontent.com/29965889/52179047-093e4200-279b-11e9-9d13-4636353241cd.png">
[Test Plan Document_StoryID_559.xlsx](https://github.com/uno-isqa-8950/uno-cpi/files/2825695/Test.Plan.Document_StoryID_559.xlsx)
FYI - @jerrodanzalone  @EdemD

**Comment by Jantz021991** [comment]
I'll fix this

**Comment by jnabity** [comment]
Testing passed QA. Script [here](https://docs.google.com/spreadsheets/d/1zCT1sIIIhYfRy45pMPkLF0KiZbF77eFGOMKaO8t6SqQ/edit?usp=sharing).
@EdemD please review and move to done.
CC: @Jantz021991 @jerrodanzalone
