### ISSUE TITLE
Reorder address fields

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#564]
#485

In general order the address information to be consistent with other address entry fields

**Comment by shashankpatibandla** [comment]
The address consistency in "Register:Community Partner" is updated according to the flow described in the above comment.
![image](https://user-images.githubusercontent.com/35643257/51954829-4c00c280-2407-11e9-85ce-560032af31cf.png)

**Comment by caadler** [comment]
Pulled locally and address fields are correct.

**Comment by EdemD** [comment]
@caadler would you please add the screenshot here please. Thanks for testing this.
