### ISSUE TITLE
Email confirmation process for new users

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#574]
Setup an email confirmation process for registering new users

**Comment by jerrodanzalone** [comment]
Note that this is for campus partners only. We need feedback from the client for community partners.

**Comment by EdemD** [comment]
@kalpanajha as QA tester

**Comment by Jantz021991** [comment]
Email Verification Process for Community Partner User -


1. Campus Partner User or Admin invites a community Partner User (User email account is generic which may be a edu account or may not be)

2. Invite sent out to the user to sign up to UNO-CPI application.

3. Community Partner User signs up and is logged in as a Community Partner User
