### ISSUE TITLE
ADA compliance for Sprint 1 work

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#575]
--research overall needs of project
  --project form/community partner form/project table

**Comment by Jantz021991** [comment]
This is our website for  following ADA Complaince- 
![image](https://user-images.githubusercontent.com/26983295/52529048-70cf2280-2cb0-11e9-9245-8dcd5ab98cbc.png)

**Comment by Jantz021991** [comment]
Considering ADA Compliance, the UI has forms that can be navigated via keyboard, @EdemD  consider this in your testing.

Look into #641 for more details.
