### ISSUE TITLE
As a user, I want to see a report of engagement types.

### ISSUE THREAD

**Issue by TarekRamesses** [uno-isqa-8950/uno-cpi#6]
Fields: 
- engagement type name
- count of projects
- number of UNO students
- number of total UNO hours

Can filter by: 
- academic year
- campus partner
- mission area
- legislative district
- household income
- CEC partner

**Comment by TarekRamesses** [comment]
This report is pre-existing: Engagement Type

**Comment by indraTeja** [comment]
![capture](https://user-images.githubusercontent.com/13390222/47622514-c43bad00-dad3-11e8-9210-888972c4c904.PNG)

**Comment by indraTeja** [comment]
![capture](https://user-images.githubusercontent.com/13390222/47624743-ada24f80-daed-11e8-9980-00630259700f.PNG)

**Comment by indraTeja** [comment]
Working good as Expected. Please add sort table.
![capture](https://user-images.githubusercontent.com/13390222/48367086-464fd800-e675-11e8-8770-eafeae85cb9d.PNG)

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49555973-85b1c300-f8c7-11e8-9c17-2e7d6c35bcec.png)

Same error as mission area report.
