### ISSUE TITLE
Create New community partner

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#615]
add a link on the project form to create a new community partner

**Comment by shashankpatibandla** [comment]
@EdemD This ticket is also merged via merge-request #651. I couldn't connect that merge request to two tickets. But hopefully this enough communicate that the ticket has been resolved from a Dev stand point.

cc'ed - @jerrodanzalone

**Comment by EdemD** [comment]
Got it so 614 and 615 are done right?
