### ISSUE TITLE
#530-C - Add functionality on Organizations page

### ISSUE THREAD

**Issue by shashankpatibandla** [uno-isqa-8950/uno-cpi#624]
This ticket is part of 530 which is CRUD functionality for organizations. But this ticket only deals with "ADD" functionality

**Comment by duwaezuoke** [comment]
After QA testing, functionality on organization's page achieved. Image below;
![screenshot 276](https://user-images.githubusercontent.com/31281458/52552893-680d4800-2da7-11e9-9396-54720728eb07.png)
