### ISSUE TITLE
Auto-populate current year on project form

### ISSUE THREAD

**Issue by jerrodanzalone** [uno-isqa-8950/uno-cpi#640]
When adding a new project, I want the academic year to auto-populate to the current year. 

![image.png](https://images.zenhubusercontent.com/5c3a12df7e0c8903585df8a1/54e2d734-5e28-4f62-b4fe-a4d08a57eac9)

**Comment by duwaezuoke** [comment]
Tested and done-done. Test case can be found in drive. Reference: https://drive.google.com/open?id=1FOmhlPfyuEMTya9qH5fJSerjD5C8wPcS
