### ISSUE TITLE
Mission Area Duplicate Entry Prevention 

### ISSUE THREAD

**Issue by jerrodanzalone** [uno-isqa-8950/uno-cpi#643]
As an admin, I want to have a constraint on mission area so that duplicate entries are not added to the database. 

![image.png](https://images.zenhubusercontent.com/5c3a12df7e0c8903585df8a1/2a3808b8-b286-4de4-90e4-0c5ce935366f)

![image.png](https://images.zenhubusercontent.com/5c3a12df7e0c8903585df8a1/fd9acbd5-c8ea-4168-9a10-0f3d93181e10)

**Comment by caadler** [comment]
We should add to this ticket that 1 primary mission area is always required.

**Comment by caadler** [comment]
@kalpanajha This ticket is to split up Mission area into two areas: Primary and Other.  There can be multiple "Other" mission areas.
