### ISSUE TITLE
Report spacing

### ISSUE THREAD

**Issue by jerrodanzalone** [uno-isqa-8950/uno-cpi#649]
When logged in as a campus partner, I want the spacing to be consistent on the "All projects" and "My Projects" reports with the Analytics reports. Right now, the analytics reports are closer than the projects reports. 

![image.png](https://images.zenhubusercontent.com/5c3a12df7e0c8903585df8a1/2edee9a3-493d-42ef-903f-45621a9a1c25)

![image.png](https://images.zenhubusercontent.com/5c3a12df7e0c8903585df8a1/14a3a205-4f07-4d8b-8a60-677fd660da84)

**Comment by jnabity** [comment]
Testing passed successfully for screens. Test script below:
https://docs.google.com/spreadsheets/d/1J0pk7_Vmm_1rSN9v8pUdCcqBR89OKNvi1_MOtFtQ504/edit#gid=547627265
FYI - @EdemD @jerrodanzalone @Ruthie2018
