### ISSUE TITLE
Changing Labels in Admin Panel

### ISSUE THREAD

**Issue by jerrodanzalone** [uno-isqa-8950/uno-cpi#650]
As an admin, I want the following two items to be relabeled to "Statuses" and "Universities"

![image.png](https://images.zenhubusercontent.com/5c3a12df7e0c8903585df8a1/e432fcde-ecbc-4efc-a644-82cf53c4d0ec)

**Comment by jnabity** [comment]
Testing passed successfully.
<img width="1679" alt="screen shot 2019-02-16 at 11 57 40 am" src="https://user-images.githubusercontent.com/29965889/52903399-8c6f8700-31e2-11e9-9611-673cfd82ed76.png">
<img width="1678" alt="screen shot 2019-02-16 at 11 57 07 am" src="https://user-images.githubusercontent.com/29965889/52903400-8d081d80-31e2-11e9-8ecb-0898a650f6de.png">

Test Script:
https://docs.google.com/spreadsheets/d/1d3xMdm471J8NRDWPUaG5CJPbHN9vj5x57Sb0tbwTD7Y/edit#gid=547627265

FYI - @jerrodanzalone @EdemD @kalpanajha
