### ISSUE TITLE
Update Password Reset Message

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#653]
Change "has" to "have" in first sentence.

**Comment by EdemD** [comment]
Manual testing completed. Validated that the wording on the password reset message has been changed as specified by the client. 

https://docs.google.com/spreadsheets/d/1fUsjWxN5TXP_1x8Jux7x1QjQnmLjcGArzdJmOpISw_I/edit#gid=547627265

![653 update password reset message](https://user-images.githubusercontent.com/19415394/52921342-a80a8880-32db-11e9-9c32-76c614911b71.png)
