### ISSUE TITLE
Hide null map field values

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#657]
![image](https://user-images.githubusercontent.com/35402227/52894369-f863d800-316d-11e9-9a2d-c2248b524a9a.png)

**Comment by vbhat0891** [comment]
Can be moved to QA once we get a confirmation on if the Clients want the labels to disappear or just the field content.

**Comment by jnabity** [comment]
@vbhat0891 can you confirm what the decision was from the Client? Are we testing that the labels appear with blank values or that the label is removed when there is no corresponding data?

**Comment by vbhat0891** [comment]
@jnabity You can test it on the grounds of no "NAN" or null being displayed in those fields. Its been 2 sprints and we have not any feedback on this. I discussed this with @caadler as well and we thought asking them would result in they wanting it or asking us to make further changes. If at all they come back on this, we will create a new ticket to work on.

**Comment by jnabity** [comment]
Tested Community Partner, Community Partner Types, and Legislative District Maps. Test script listed below:
https://docs.google.com/spreadsheets/d/17kFmYIYLLgX7M4gSetHpXWf-1OUrojm_Q_GmYz1GkN8/edit#gid=276410489
