### ISSUE TITLE
Move and Relabel Mission Area Box on Project Form

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#659]
Move mission area box below Campus and Community Partner sections.  Relabel to "Project Mission Area"

**Comment by shashankpatibandla** [comment]
@EdemD  Fixed this with merge request #670 

@jerrodanzalone

**Comment by EdemD** [comment]
https://docs.google.com/spreadsheets/d/1s7eEhUKKtBAhc5OYG0S1tG5pnYgcUMXeuDD2zraNPx0/edit#gid=547627265
![659 move and relabel mission area in project form](https://user-images.githubusercontent.com/19415394/52920686-14ce5480-32d5-11e9-8f16-9a87bb778879.png)
