### ISSUE TITLE
Remove Campus Facilitator from Project List

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#660]
Remove Campus Facilitator from Project List:
![image](https://user-images.githubusercontent.com/35402227/52894516-306c1a80-3170-11e9-929a-29d90b5dd16f.png)

**Comment by EdemD** [comment]
Validated that the Campus Facilitator field is no longer on the Project Details List
https://docs.google.com/spreadsheets/d/1kDlD1jvFjbBhtBgEXI1najTKH6EVz-OvjXULBhIfI7w/edit#gid=547627265
![campus facilitator field removed](https://user-images.githubusercontent.com/19415394/52917240-bbebc580-32ae-11e9-95fd-c3c7e08b3078.png)
