### ISSUE TITLE
As a community partner, I want to see a report listing community partners.

### ISSUE THREAD

**Issue by TarekRamesses** [uno-isqa-8950/uno-cpi#7]
Community partners should have the following fields: 
- mission area
- number of projects
- number of campus partners collaborated with

Can filter by: 
- academic year
- campus partner
- mission area
- legislative district
- CEC partner

There will be additional private (campus only) information.

Private fields: 
- number of UNO students
- number of hours
- economic impact (hours * wage)
- community contact

**Comment by indraTeja** [comment]
Mission filter is not working as expected. 

![capture](https://user-images.githubusercontent.com/13390222/48375160-a9993480-e68c-11e8-9bd6-233f169481fa.PNG)

**Comment by indraTeja** [comment]
Fix Academic Year !~!!

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49332020-a72f4980-f56b-11e8-8568-76b2cfc0b091.png)

Mission area filter doesn't change data. Academic year doesn't select. There is no all option for CEC partner.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49353273-84438900-f682-11e8-8bfe-0b8fa27a9964.png)

Mission area filter does nothing.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49555921-4edbad00-f8c7-11e8-8dd9-db34b14b4447.png)

Says it just doesn't exist.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49560366-abdf5f00-f8d7-11e8-8897-fe0c077521ad.png)

Missing fields: number of campus partners, website.

**Comment by TarekRamesses** [comment]
![image](https://user-images.githubusercontent.com/22284674/49560588-aafafd00-f8d8-11e8-9eed-88be6483f582.png)
![image](https://user-images.githubusercontent.com/22284674/49560596-b5b59200-f8d8-11e8-8379-fc2e17b0f5fa.png)
![image](https://user-images.githubusercontent.com/22284674/49560606-c0702700-f8d8-11e8-9571-0f02bd03bf74.png)

The academic year projects should add up, and they don't. 2016-2017 projects for abide network should be 3.
