### ISSUE TITLE
Legislative Districts Map with Google maps API

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#702]
this ticket is the epic for all updates to the legislative districts map

**Comment by EdemD** [comment]
@vineethreddyramasa assigned as QA.

**Comment by vineethreddyramasa** [comment]
All the filters work and data pointers respond to filters. Search functionality ignores the filters. Clustering doesn't work properly when filters are applied.

**Comment by jnabity** [comment]
@vineethreddyramasa this is ready for testing :)

**Comment by vbhat0891** [comment]
College filter is not working on this map, rest works as expected.

**Comment by vineethreddyramasa** [comment]
@EdemD All the filters work. Test Case Document https://drive.google.com/open?id=1OApFGlJLUDVLv2JvM2UdjUN9KPdIyAoRlInZwgc9BTI
