### ISSUE TITLE
Project Maps with Google maps API

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#703]
project map with google maps api implemented

**Comment by EdemD** [comment]
@shashankpatibandla  assigned as QA.

**Comment by vbhat0891** [comment]
Filters don't work well on this map.

**Comment by shashankpatibandla** [comment]
Tested with some anomolies with filters as suggested above. This is the document link for testing.
https://drive.google.com/drive/u/2/folders/1TA94Se8gdS3N0uGP2xRgSnoLvuY_uFdL
