### ISSUE TITLE
Update CMS Front Page Design

### ISSUE THREAD

**Issue by jerrodanzalone** [uno-isqa-8950/uno-cpi#714]
As an administrator, I want to be able to edit the front page and add content, images, and featured stories as desired over time. I want these images to be stored on an Amazon S3 Bucket.

**Comment by caadler** [comment]
@EdemD QA testing passed.

**Comment by EdemD** [comment]
https://drive.google.com/open?id=1bE0PuUEN2Mf-D1mUIitMKeTwPpLheJdHmuv0uv5qZkM
