### ISSUE TITLE
Create projects form remove fields

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#725]
remove nonmandatory fields and put them in a separate editable form

**Comment by EdemD** [comment]
@Ruthie2018, we have discover that on the Create Project Form, clicking on the Add Additional Mission Area is submitting the form. 
![image](https://user-images.githubusercontent.com/19415394/54216429-9e79d800-44b7-11e9-9f98-64b4879caa32.png)
