### ISSUE TITLE
Remove Shadowing throughout

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#728]
should be consistent across the app and ADA/UComm compliant

**Comment by jerrodanzalone** [comment]
headers, buttons, 

see engagement type report

**Comment by Jantz021991** [comment]
Shadows removal -

1. Create Project Page- 
![image](https://user-images.githubusercontent.com/26983295/54166044-53b57d00-4431-11e9-8810-c934e7b817d5.png)

2. Project create done -
![image](https://user-images.githubusercontent.com/26983295/54166032-413b4380-4431-11e9-86e5-5c7059d3f83c.png)

**Comment by caadler** [comment]
@Jantz021991  I found shadows on the Register Community Partner User page, the My Profile page, Organization page, Log Out page, Campus Partner User registration, Log In page.
