### ISSUE TITLE
Engagement Type Report - Add Filters

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#758]
Engagement Type: add campus partner (college/main unit), community partner type, add CEC building partner

**Comment by jnabity** [comment]
Tested report filter updates. Cascade function between College and Campus Partner filters is still underdevelopment. Test script below for ticket functionality.
https://docs.google.com/spreadsheets/d/1QtPmY6zi5zYpC-KETJnoxezZekPsh_aDbQp0GvQ1Ri8/edit#gid=227356338
FYI - @EdemD @jerrodanzalone
