### ISSUE TITLE
Register Campus Partner Form - Fix College Name

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#763]
The college name dropdown on the Register Campus Partner form extends beyond the form box.  

![image](https://user-images.githubusercontent.com/35402227/53930931-bfc26a80-4058-11e9-9e77-b436b7cfefc0.png)

**Comment by EdemD** [comment]
@pallavi0902 as QA tester

**Comment by EdemD** [comment]
Test document: https://drive.google.com/open?id=1KjFc7BZp7wx1TS2Frx2RhCfzVBjXcTNiEwzBZSYYDd4
