### ISSUE TITLE
Community Partner Report - Remove partners without projects

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#766]
Community partner report should filter out community partners with project number = 0

**Comment by jnabity** [comment]
@caadler to get further clarification from client on this feedback request.

**Comment by caadler** [comment]
@EdemD I tested, and everything looks good.

**Comment by EdemD** [comment]
https://drive.google.com/open?id=1bHaWer3L1IvraP9s-bTKQgt_svx3hBWEM0v7KtBD0OM
