### ISSUE TITLE
add college structure to charts

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#821]

**Comment by shashankpatibandla** [comment]
@jerrodanzalone & @EdemD . This ticket is merged with pull request #861

**Comment by duwaezuoke** [comment]
QA tested and confirm done-done. Reference to drive: https://drive.google.com/open?id=1ckMV0Xl5-booiomMmjTbtHAyW-LmHE52j-Am5JSN38E
