### ISSUE TITLE
add college structure to maps

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#823]

**Comment by vbhat0891** [comment]
Facing difficulty with writing the conditional statements for chained filtering. Hari is helping with this, Jerrod and I will be giving this a try in the next sprint.

**Comment by caadler** [comment]
@EdemD This ticket passed QA.  Cascading filter functionality will be processed on separate ticket.
https://docs.google.com/spreadsheets/d/1Ewtwl2e3tI6gH4JyXTKAhPibsQ2MBPpWw2SJxmL-8No/edit?usp=sharing

**Comment by EdemD** [comment]
Thanks @caadler
