### ISSUE TITLE
Engagement type chart data discrepancy

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#824]
step 1 of epic #466 
1 - First, the chart data does not align with the report data.

**Comment by shashankpatibandla** [comment]
@jerrodanzalone & @EdemD . This ticket is merged with pull request #861

**Comment by duwaezuoke** [comment]
QA tested and confirmed done-done. Reference link: https://drive.google.com/open?id=1Qn3UBhRoeCaN_aaBpdo3krCDLO5KsxTZUwkCluZPleY
