### ISSUE TITLE
engagement type chart filter error

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#825]
steps 2-3 of epic #466 

2- Second, it does not seem to be accurate. The Campus Partner filter is not working accurately. Regardless of what is selected, the community partner and campus partner count does not change.
3- Also, the alignment in number of project/community_partner/campus_partner seems inaccurate, especially since it is consistent regardless of filtering.

**Comment by shashankpatibandla** [comment]
@jerrodanzalone & @EdemD . This ticket is merged with pull request #861

**Comment by EdemD** [comment]
Test document: https://drive.google.com/open?id=1b1gY5Uk3frQYJbQciGpzkKq0UfeD-8Cf-K_UuAdS6qo
