### ISSUE TITLE
create GeoJSON scheduler

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#830]

**Comment by vbhat0891** [comment]
It's nearly done, have some issues with the scheduler.

**Comment by vbhat0891** [comment]
After working on this for a couple of sprints, this is officially done! Go ahead and test it by adding Community partner/Project or any scenario which needs an update in the information displayed on the map.

**Comment by pallavi0902** [comment]
QA Test Passed. https://drive.google.com/drive/u/0/folders/1HphhQDVJeHHbNlNzu_A7_GC3DoOeeJUK
