### ISSUE TITLE
Login screen centering

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#832]
continue applying formatting to center all screens

**Comment by caadler** [comment]
Per client feedback, there is too much whitespace

**Comment by Jantz021991** [comment]
@kalpanajha, these are the changes made for this ticket 

![image](https://user-images.githubusercontent.com/26983295/54869525-c7c41f00-4d67-11e9-8e33-e7f367b1e0eb.png)

Changed the color of the links from blue to red

**Comment by kalpanajha** [comment]
White space for login page is changed and the links are changed from blue to red.

https://drive.google.com/drive/folders/1uAg5-vFjjHsahe1qLhinm6b7YqaicrV9

**Comment by kalpanajha** [comment]
https://drive.google.com/open?id=1ML9kfH_5bqB3tg0hsyIGcBW5ylxEjd1J
