### ISSUE TITLE
Create server side list page

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#834]
to help speed up app responsiveness on projects report

**Comment by jnabity** [comment]
Researching this during Sprint 4.

**Comment by vbhat0891** [comment]
I have optimized the code wherever possible and removed the print statements(it does take CPU clock cycles to print all the projects in the console every time) - there were 35 of them just in project views. If this does not solve our issue, I would implement the server side paging.

**Comment by jnabity** [comment]
Research completed on this issue.
