### ISSUE TITLE
Completed projects

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#836]
add logic to move projects to completed status automatically when they're done (end of semester?)

**Comment by jnabity** [comment]
@EdemD I confirmed with the clients, when there are future projects they should be set to a status of 'Pending'. So we need to add the status of 'Pending' and update the code for future projects.
FYI - @jerrodanzalone  @caadler

**Comment by jnabity** [comment]
@EdemD this has been merged and is ready for testing.

**Comment by EdemD** [comment]
Ahead of you @jnabity :D . Saw your code come through this AM and already started looking at the code itself. Very clean code man. Look at it this too long  and could not have refactored it this way. I think this covers everything as it ran locally very well and it ran as against STA as well.
Will throw some additional tests scenarios out there in STA. I think we were good on all but Pending so will focus on that. I'll suggest that you change a few current projects as well. The more the merrier. If all changed successfully we can close the ticket tomorrow. Thanks

**Comment by EdemD** [comment]
Test document: https://docs.google.com/spreadsheets/d/1sYbc98jLTcy3trMWMmH_ZNk7sE_q2J4xo3eSblnpKBE/edit#gid=547627265
