### ISSUE TITLE
Create Project layout

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#837]
semester box arrow drop down should be the same format as the other drop downs.

All box and text alignment should be the same.  Use the same font throughout (same for the application as a whole)

**Comment by kalpanajha** [comment]
semester box arrow drop down is same format as the other drop downs.

All box and text alignment are same. 
Additional Mission area button removed from the create project form

https://drive.google.com/open?id=19AVCfgdV91igsUPz9rqDuSsdSLR1CfS1
