### ISSUE TITLE
Community Partner Map Conversion

### ISSUE THREAD

**Issue by jerrodanzalone** [uno-isqa-8950/uno-cpi#847]
Match formatting of Legislative District and Project maps in terms of clustering and marker formatting.

**Comment by jnabity** [comment]
Testing passed for this ticket. Formatting looks consistent between Community Partner and Legislative District maps.
https://docs.google.com/spreadsheets/d/1qrv9F8yRxsT1WMAQ95sQC2RoEdhAFDoFF1jp98SoQ_c/edit#gid=227356338
FYI - @jerrodanzalone @EdemD
