### ISSUE TITLE
Community Partner Type Map Conversion

### ISSUE THREAD

**Issue by jerrodanzalone** [uno-isqa-8950/uno-cpi#848]
Convert Community Partner Type map to the same styling as Projects and Legislative District map in terms of clustering and markers.

**Comment by EdemD** [comment]
@shashankpatibandla as QA tester

**Comment by shashankpatibandla** [comment]
Tested this and all the filter work. https://docs.google.com/spreadsheets/d/1W9XSOJrFM-dv_XUkFmS3cvA5woezKfn_8JoFJdVuhh8/edit#gid=847918155. This is the link for the tested document
