### ISSUE TITLE
Map Spider Effect - Need Indicator

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#868]

**Comment by vbhat0891** [comment]
A workaround is implemented on the legislative districts map where the markers are offset by a small margin to avoid overlapping. If the Clients are happy with it, we will extend this functionality to other maps.

**Comment by vbhat0891** [comment]
This functionality has been extended all the maps.

**Comment by duwaezuoke** [comment]
QA tested and confirmed done-done. Reference: https://drive.google.com/open?id=1TqiiXhfDSVA6lm8FZsojDpbhpEAFFHYuFAePMCwkwLk
