### ISSUE TITLE
Updating Projects for Community Partners

### ISSUE THREAD

**Issue by TarekRamesses** [uno-isqa-8950/uno-cpi#87]
Community partners can edit certain fields in a project, including adding mission areas and number of hours/people.

**Comment by indraTeja** [comment]
UI fixes needed.

![capture](https://user-images.githubusercontent.com/13390222/46824980-0b960f80-cd58-11e8-95dd-5ed05f430974.PNG)

**Comment by indraTeja** [comment]
Please add the dashboard or redirect to the dashboard in the upcoming sprint

![capture](https://user-images.githubusercontent.com/13390222/46825183-9ecf4500-cd58-11e8-995d-fad19a7e14a5.PNG)
