### ISSUE TITLE
Maps - Limit max zoom out

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#870]
max zoom out for maps should be the globe.  Currently:
![image](https://user-images.githubusercontent.com/35402227/54655160-d2906280-4a8e-11e9-95fc-c851a0c1523b.png)

**Comment by vbhat0891** [comment]
This issue is fixed, the user cannot zoom out more than zoom level 3.

This is the minimum zoom level for all the maps-
![image](https://user-images.githubusercontent.com/26983338/54882455-2cdf4980-4e28-11e9-9379-1cabd8b9e324.png)

**Comment by EdemD** [comment]
@kalpanajha @ QA tester

**Comment by kalpanajha** [comment]
max now maps zoom out to is the globe.

https://drive.google.com/open?id=1ZWLlOZHq-gtd-YFuIJGnyi4IoRfvVH-x
