### ISSUE TITLE
Map Group Icon - Change Color

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#872]
Make the group icon a color that is distinct from any of the dots.
![image](https://user-images.githubusercontent.com/35402227/54655686-d9b87000-4a90-11e9-8359-32e8c097f650.png)

**Comment by vbhat0891** [comment]
Changed the marker color of one of the marker to black, none of the marker color is yellow. The clustering color is retained as yellow.

![image](https://user-images.githubusercontent.com/26983338/54882355-243a4380-4e27-11e9-99d5-ea0c27cb0f3b.png)

Legislative district map
![image](https://user-images.githubusercontent.com/26983338/54882364-416f1200-4e27-11e9-866f-bedff183c3a8.png)

**Comment by duwaezuoke** [comment]
QA tested and confirmed done. Reference: https://drive.google.com/open?id=1bQqsp0BJVHhz0xUFZYeApBnDuBBvDr7vkWL-2d4dUNc
