### ISSUE TITLE
Multiple contacts/multiple mission areas for campus partner

### ISSUE THREAD

**Issue by TarekRamesses** [uno-isqa-8950/uno-cpi#88]
Javascript issues with adding multiple mission areas to a project, or multiple contacts to a campus organization profile.

**Comment by indraTeja** [comment]
Campus partner login, view projects, and edit projects are working fine.

**Comment by indraTeja** [comment]
Profile edit functionality is fine. But, edit or add projects needs UI improvement.

**Comment by indraTeja** [comment]
Login page for campus could be redirected to dashboard in upcoming sprints.

![capture](https://user-images.githubusercontent.com/13390222/46824795-96c2d580-cd57-11e8-85bc-7d98539269e1.PNG)
