### ISSUE TITLE
Report & Chart Descriptions

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#910]
Short paragraphs (should be admin/CMS controlled) to be included on the analytics pages:
 
Mission Areas
This report shows the number of community partners, projects and students based on the primary mission of their work. Various filters are provided to gain a better understanding on how various UNO units collaborate with the community.  
 
 
Engagement Types
This report shows the number of projects, community partners, and campus units associated with each type of engagement. The types of engagement categorize the project and range from course-based engagement to knowledge sharing to service.
 
Please add a definition box for each type of engagement in the table itself.
 
Community Partners
This report shows all UNO community partners with the number of projects they were engaged in. Various filters are provided to gain a better understanding on the type of community organizations, the primary focus of their work, and how various UNO units are collaborating with the community.
 
* Projects *
This report shows the various collaborative projects between UNO and the community.
 
* I’m still a little unclear about this one since it has never really shown up the way we discussed – so this description is likely to change once the issue is figured out. *
 
 
 
CHARTS
Mission Areas
This report shows the number of community partners and projects based on the primary mission of their work. Various filters are provided to gain a better understanding on how various UNO units collaborate with the community.  
 
Engagement Types
This report shows the number of projects, community partners, and campus units associated with each type of engagement. The types of engagement categorize the project and range from course-based engagement to knowledge sharing to service.

**Comment by EdemD** [comment]
@pallavi0902 @QA tester

**Comment by jnabity** [comment]
closed duplicate with #1042
