### ISSUE TITLE
Update all pagination buttons color

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#912]
update to #333333 to match headers and other buttons in #529

**Comment by EdemD** [comment]
@jnabity as QA tester. Thanks

**Comment by jnabity** [comment]
Validated pagination color change. Testing passed and script linked below:
https://docs.google.com/spreadsheets/d/16_6v5mhzlvBSBhFBQ4cgaFhtyBq1pwkbvL1Uq01o4yw/edit#gid=1097804438
FYI - @jerrodanzalone  @EdemD
