### ISSUE TITLE
Update Project Report Accessibility

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#913]
Everyone should have access to the public project report, including all logged in users.  The private report is not needed.

**Comment by EdemD** [comment]
![913_Screen](https://user-images.githubusercontent.com/19415394/55192146-d6e50b80-5171-11e9-94d7-36bb2c77c13d.png)

**Comment by EdemD** [comment]
Test document: https://drive.google.com/open?id=1NoIhmTszHDsWwH6IDIFzIUUquMSI4NkKxv1NMkxsGsM
