### ISSUE TITLE
All Reports - Use Primary mission area

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#914]
All mission area filters on reports / charts should use primary mission area only.

**Comment by EdemD** [comment]
@kalpanajha as QA tester

**Comment by kalpanajha** [comment]
All mission area filters on reports / charts uses primary mission area only.

https://drive.google.com/open?id=1BNmiV5kVC2jz9RwM5rBrilBXnC8OEhg6
