### ISSUE TITLE
Community Partner Report accessibiilty

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#915]
All logged in users should be able to access the private community partner report.  Non-Logged in users will access the public report.

**Comment by EdemD** [comment]
@kalpanajha as QA tester

**Comment by EdemD** [comment]
![image](https://user-images.githubusercontent.com/19415394/55193124-1ad91000-5174-11e9-8cf0-1b43f5ac4714.png)

**Comment by EdemD** [comment]
Test document: https://drive.google.com/open?id=1Uk_D1u3DJAw5ba9qCLMawSuXFJhK7EwnpPxbDJIxoTg
