### ISSUE TITLE
Enlarge First Column in Reports

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#916]
Make the first column in reports larger.

**Comment by EdemD** [comment]
@jnabity as QA tester

**Comment by wlcobb** [comment]
@sirichandana95 Masses of white space and would like to utilize the space better.  But still need to consider how it will look in mobile and tablet.  We are already modernizing and maybe close the ticket and refer to the modernization chart and reports.

**Comment by sirichandana95** [comment]
Thanks for the information Wendy.
