### ISSUE TITLE
Homepage / CMS Updates

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#928]
Scroll over links (Register a new campus, etc… in the light gray section and Engagement, CPI Goals, etc.. in the bottom area
-          Rollover color is blue and should be dark red or red.
 
Photo buttons for Economic Impact, etc..
-          The underline upon rollover is blue and should be red, black, or dark gray.
-          Also, I would say there’s not enough contrast between the photo and the type. I would either darken the photo behind or make the text a little bolder.

**Comment by EdemD** [comment]
@duwaezuoke as QA tester

**Comment by duwaezuoke** [comment]
QA tested and confirmed done. Reference: https://drive.google.com/open?id=1_xKZDKVAUeX96jYwXhOGFJ6CuQ2hNzgGILnnYh9jsko
