### ISSUE TITLE
Partners Page Updates

### ISSUE THREAD

**Issue by caadler** [uno-isqa-8950/uno-cpi#929]
Campus Partner User Signup link
-          Link color blue, should be dark red or red.

**Comment by jerrodanzalone** [comment]
This appears to have been done.

**Comment by EdemD** [comment]
@kalpanajha as QA tester

**Comment by kalpanajha** [comment]
Campus Partner User Signup link color has been changed to red instead of blue

https://drive.google.com/open?id=1HCfMiWPd6jOvKa8paSktLJAFtQGVhSrd

**Comment by shashankpatibandla** [comment]
@EdemD Assign a Q/A for this. Need to check the image in the header and the footer should be consistent. Also check for mobile reponsiveness
