### ISSUE TITLE
Add CMS as a drop-down option for Admin users in navbar

### ISSUE THREAD

**Issue by jerrodanzalone** [uno-isqa-8950/uno-cpi#950]
![image](https://user-images.githubusercontent.com/41122083/54888866-114b6180-4e6f-11e9-9576-7f1a817d1690.png)

Add 'CMS' drop-down option here.

**Comment by EdemD** [comment]
@Ruthie2018 as QA tester

**Comment by Ruthie2018** [comment]
QA passed

https://docs.google.com/spreadsheets/d/1Hec5QDAQmvg9BG7VIiM0XndcQMvrSI3XGAWANT8iJTk/edit#gid=547627265
