### ISSUE TITLE
Fix Project Form

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#959]
Please move csv button so there is more space with show all.

**Comment by Ruthie2018** [comment]
move "show" to not be so close to the CSV export button.  Check that it displays the same on all views.  See projects report

**Comment by duwaezuoke** [comment]
QA tested and confirmed done. Reference: https://drive.google.com/open?id=1Y8cJu8hsuMldT65btMfgeFdUDQIkG4r5BA_4gowdFDQ
