### ISSUE TITLE
Make the displacement of marker less subtle

### ISSUE THREAD

**Issue by vbhat0891** [uno-isqa-8950/uno-cpi#985]
Per 03/27 demo feedback, we were asked to reduce the displacement of the marker.

This is done for the legislative district map, refer the snip below 
![image.png](https://images.zenhubusercontent.com/5c36a977fdd1bf63fa7e1754/c7907c1e-5846-4823-9ecd-fc12d3b183e8)

**Comment by EdemD** [comment]
Test document: https://drive.google.com/open?id=1rd3t_KRLM7Okh3mlZNPJfE5d1lRFYyicPEo7j9-wbZs
