### ISSUE TITLE
ADA compliance for S5

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#994]

**Comment by EdemD** [comment]
@jnabity as QA tester

**Comment by Jantz021991** [comment]
@jnabity  I have made the changes to get the default avatar for the logged in user. Please test it out and let me know your thoughts

**Comment by jnabity** [comment]
@Jantz021991 
On the home screen, we are still seeing the alt text, as well as it is showing the full name. This is regardless of the type of user. Could be we are using a different nav bar for that screen. Still checking the other pages.
![Screen Shot 2019-04-01 at 1 09 37 PM](https://user-images.githubusercontent.com/29965889/55349508-832f3680-547f-11e9-8698-047a25db064b.png)

**Comment by jnabity** [comment]
Testing has passed for the updated user initials when profile photo is missing.
https://docs.google.com/spreadsheets/d/1jP0lq5qaSxkY4kxHM6OeHUihXzp8UaygQJ849V2HHA0/edit#gid=1494392258
FYI - @EdemD @jerrodanzalone @Jantz021991
