### ISSUE TITLE
Consistent UI labels

### ISSUE THREAD

**Issue by Ruthie2018** [uno-isqa-8950/uno-cpi#996]
all the labels, drop down menus, filters, etc should use the same titles throughout the application.  See #527, #528, #529 for suggestions and wording preferences.

**Comment by caadler** [comment]
Can we relabel: College Names to ‘Colleges and Main Units’

Mission Area labels to be renamed as Project or Community Partner Mission Area

**Comment by caadler** [comment]
Engagement-Type report COMPLETE

**Comment by EdemD** [comment]
Test document: https://drive.google.com/open?id=1Ym_TWrHELQIjOHVJT60L4czuPK_U6jwePXSZHUDn6Sc
